### ISSUE TITLE
Get page text for a particular revision

### ISSUE THREAD

**Issue by rjsbhatia** [mwclient/mwclient#100]
Hi, 

I am new to mediawiki and mwclient. 
Pages lets me get the latest version of the page, but I was wondering if there is a way to get an older version of the page by specifying revision id. 

Thanks, 
RJS

**Comment by danmichaelo** [comment]
Not currently, but reminds me that we actually have an open pull request for it (#84). I'll try to merge it in tomorrow.

**Comment by rjsbhatia** [comment]
That is what i was looking for. Thank you!!
