### ISSUE TITLE
Question: looking up recent changes

### ISSUE THREAD

**Issue by hugovk** [mwclient/mwclient#102]
Is it possible to get the page diffs from recent changes?

This code:
```python
import mwclient
from pprint import pprint

site = mwclient.Site("en.wikipedia.org")
recentchanges = site.recentchanges()
change = recentchanges.next()
pprint(change)
```

Gives something like:
```
{u'ns': 0,
 u'old_revid': 689697696,
 u'pageid': 35745345,
 u'rcid': 773563481,
 u'revid': 689816909,
 u'timestamp': time.struct_time(tm_year=2015, tm_mon=11, tm_mday=9, tm_hour=16, tm_min=9, tm_sec=28, tm_wday=0, tm_yday=
313, tm_isdst=-1),
 u'title': u'List of shipwrecks in the Great Lakes',
 u'type': u'edit'}
```

Can the diff be looked up from the `rcid`? Or can I get both page revisions from `revid` and `old_revid` somehow?

Thank you!

**Comment by danmichaelo** [comment]
If you get the very latest mwclient, you can do

```python
from mwclient import Site
site = Site(('https', 'en.wikipedia.org'))
for page in site.revisions([689816909]).values():
    print page['revisions'][0]['diff']['*']
```

If you need to process the diff in some way, you could fetch the texts from both diffs


```python
from mwclient import Site
site = Site(('https', 'en.wikipedia.org'))
texts = [rev['*'] for page in site.revisions([689697696, 689816909], prop='content').values() for rev in page['revisions']]
```

and compare using a diff library like difflib.

**Comment by Rbrace** [comment]
So I have been attempting what you put Dan, but the only output I get no matter what I try is Magnus Manske's Wikipedia page? Am I being dumb, is this a joke, or simply a weird way to tell me I have reached my API call limits?

**Comment by danmichaelo** [comment]
Lol, I've absolutely no idea :) Did you get that when using the exact same code as in my examples above??

Btw. I just made [a small update](https://github.com/mwclient/mwclient/commit/c23abae3b95203952c9971f143f3a162dd5d2960) to the site.revisions method, so that a double for loop is no longer needed. I've updated the example code above accordingly.

**Comment by Rbrace** [comment]
Got it working. Must be because I forgot to use brackets here:  
    for revision in site.revisions([689816909]):

so it must've sent me to that page for some reason. 
Thanks for the response.

**Comment by hugovk** [comment]
Thank you! 

First snippet is working fine and is what I'm after.

The second gives KeyError:

```
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mwclient import Site
>>> site = Site(('https', 'en.wikipedia.org'))
>>> texts = [rev['*'] for rev in site.revisions([689697696, 689816909], prop='content')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 733, in revisions
    revision['timestamp'] = parse_timestamp(revision['timestamp'])
KeyError: 'timestamp'
>>>
```

Because `revision` only contains `[u'*', 'pageid', u'contentformat', 'pagetitle', u'contentmodel', u'diff']`.

**Comment by danmichaelo** [comment]
> The second gives KeyError:

Thanks for noticing that! I'll fix

**Comment by danmichaelo** [comment]
> Must be because I forgot to use brackets here

I see. Could be an idea to let the argument support a single number as well..

**Comment by hugovk** [comment]
Maybe fix with unit tests? :)
