### ISSUE TITLE
page.save() hanging on pages using <pre> tags and/or containing code

### ISSUE THREAD

**Issue by DavidMetcalfe** [mwclient/mwclient#104]
It appears that when a loop using `page.save(text + 'Example text', summary = 'Example summary')` hits a page in my workplace Wiki that contains one or more blocks of code in preformatted blocks (`<pre></pre>`), the script hangs for a long period of time. Most of these pages contain example SQL for fixing issues, but it has been seen on other languages as well.

If given enough time, it does eventually progress through the loop, saving the desired edit, but just making you folks aware of what appears to be a performance bottleneck.

**Comment by danmichaelo** [comment]
Strange :) But mwclient does no processing of the text before passing it on, so that's quite certainly an issue with mediawiki, not mwclient. Are you on a recent mediawiki version?

**Comment by DavidMetcalfe** [comment]
@danmichaelo Yep, most current version. Issue does not occur on all articles that don't contain the content, and no delays when I manually edit instead of going through the script.

I'm also not sure I follow about the processing bit. The page.save() in my example is clearly concatenating the article text with the example string. Are you positive that would have no relation to these bottlenecks?

**Comment by danmichaelo** [comment]
What I mean is that the bottleneck is most likely on the server side, related to MediaWiki doing some kind of processing.

To test this, you could try to make the same edit with curl on the command line without mwclient. Put some wiki text that you know cause a lag in a file called `postdata` and carry out the following. You will need to add your own user, pass, api endpoint and page name. And you need to replace `(INSERT TOKEN HERE)` with values you get back from the api.

```
USER=YourUsername
PASS=YourPassword
ENDPOINT=https://test.wikipedia.org/w/api.php (USE YOUR OWN)

curl -c cookiejar -d "format=json&action=login&lgname=$USER&lgpassword=$PASS" $ENDPOINT
 
curl -b cookiejar -c cookiejar --data "action=login&format=json&lgname=$USER&lgpassword=$PASS&lgtoken=(INSERT TOKEN HERE)" $ENDPOINT

curl -b cookiejar -c cookiejar --data "format=json&action=query&meta=tokens" $ENDPOINT

curl -b cookiejar -c cookiejar --data-urlencode 'text@postdata' -d 'format=json&action=edit&title=(NAME OF PAGE)&token=(INSERT TOKEN HERE)' $ENDPOINT  
```

(note that the last token must be urlencoded)

**Comment by DavidMetcalfe** [comment]
@danmichaelo Thanks for the info. As these are workplace Windows machines, everything's locked down, so I can't set up curl, but I might be able to run a portable version off USB to attempt it.

Otherwise I'll try Requests in Python.

**Comment by danmichaelo** [comment]
Closing this for now. Feel free to re-open the issue if there are updates.
