### ISSUE TITLE
Python 2 gives objects, python3 gives dictionaries

### ISSUE THREAD

**Issue by pfctdayelise** [mwclient/mwclient#106]
I don't know if I'm missing something obvious, but under python3 I seem to get dictionaries of data back rather than nice Image or Category or Page objects.

```python
import pytest
import mwclient


site = mwclient.Site('en.wikipedia.org')
page = site.Pages['Marcos Baghdatis']


def test_images():
    images = list(page.images())
    image = images[0]
    assert type(image) == mwclient.image.Image


def test_categories():
    cats = list(page.categories())
    cat = cats[0]
    assert type(cat) == mwclient.listing.Category
```

I made a virtualenv with python2, these tests pass. Under python3 they fail. 

```
(aomp):~/workspace/aomp$ py.test test_version.py --tb=line
============================================= test session starts ==============================================
platform linux -- Python 3.4.3, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /home/workspace/aomp, inifile: 
collected 2 items 

test_version.py FF

=================================================== FAILURES ===================================================
/home/workspace/aomp/test_version.py:12: assert <class 'dict'> == <class 'mwclient.image.Image'>
/home/workspace/aomp/test_version.py:18: assert <class 'dict'> == <class 'mwclient.listing.Category'>
=========================================== 2 failed in 4.09 seconds ==========================================
```

**Comment by tosher** [comment]
The same as in https://github.com/mwclient/mwclient/issues/99?
Comment at 1 Nov 2015..

**Comment by waldyrious** [comment]
@tosher you can [link directly to a comment](https://github.com/mwclient/mwclient/issues/99#issuecomment-152850031) by clicking on the date :)

**Comment by tosher** [comment]
Oh, thanks! :)
fixed..

**Comment by pfctdayelise** [comment]
@tosher sounds like the same issue. I don't quite follow that other issue, is it resolved on some branch waiting to be merged? or what's the story?

**Comment by tosher** [comment]
This error was catched in experimental branch with relative imports (i'm using it in my plugin for Sublime text). I'm fixed this error in me rep.
But i didn't know about existing it in master branch. This case confirms it :)

Possible fix: https://github.com/mwclient/mwclient/issues/99#issuecomment-154751657

**Comment by AdamWill** [comment]
I am seeing this too, it's a deal-breaker for moving my mwclient-based code to py3. The specific case I'm hitting is iterating over pages 'in' a category:

    import mwclient
    import sys

    site = mwclient.Site(('https', 'fedoraproject.org'), '/w/')
    cat = site.pages['Category:Package_yum_test_cases']
    for page in cat:
        print(type(page))
        print(page)
    sys.exit()

running that with py2 I get Page instances, with py3 I get dicts.

**Comment by AdamWill** [comment]
@tosher I think you're right. The problem came in with https://github.com/mwclient/mwclient/commit/8d0650cdd3921066b310f9cbbea33ef1ae274ff5 , I think. That commit effectively renamed the existing `List.next` method to `List.__next__` and added a simple wrapper `next` method for py2 compatibility. But it didn't change the calls to `List.next` in those methods. So the target of those calls changed; your suggested change would effectively restore the previous behaviour. (I dunno why the behaviour changes depending on whether the call is to the 'real' method or the wrapper method, but hey, I'm just the monkey).

Your change works for me too. Can you send a PR with just that change, or do you mind if I do it? Maybe @danmichaelo has time to simply merge a PR :)

**Comment by AdamWill** [comment]
@tosher I created a PR and credited you in the commit message, hope that's OK :)

**Comment by tosher** [comment]
Ок! :)
Thank You.

**Comment by waldyrious** [comment]
@tosher just out of curiosity, was the "Ok" written in Cyrillic characters intentionally, or was it perhaps due to autocorrect?

**Comment by tosher** [comment]
Not intentionally and not autocorrection, i don't know how i did it :)
Frequent switching maybe :)

P.S. fixed :)))))

**Comment by eighthave** [comment]
@lamby and I are working on the python side of F-Droid, and are eagerly awaiting this fix :)  Would more testing help move it along?

**Comment by AdamWill** [comment]
It can't hurt! But I think we just hit one of @danmichaelo 's busy periods :/ this is somewhat tricksy stuff, though, so it'd certainly be good to have people try different use cases to make sure the fix doesn't break anything, and doesn't miss any cases.

**Comment by waldyrious** [comment]
I can merge this if you guys all vouch for it. I suppose @danmichaelo can revert if anything goes wrong, anyway.

**Comment by waldyrious** [comment]
In fact, if someone can write some tests for the new code, we'd both resolve the coveralls failure in #108, and get more confidence that the code doesn't break anything.

**Comment by AdamWill** [comment]
@waldyrious unfortunately there's no test code for *any* of the `listing` stuff, so it would be a case of writing the whole thing from scratch, and the test bits for mwclient aren't that easy to grok (there's a whole lot of mocking site objects and stuff which I think dan groks better than anyone).

I think it'd make sense to wait at least a week or two for feedback from more folks before merging...in a sense it's not too dangerous as the current code is *clearly* badly broken and probably unusable for most mwclient use cases on py3, but it's vaguely possible the patch could break some unconsidered case even worse, I guess :)

**Comment by waldyrious** [comment]
:+1: I'll wait for others in this thread to report their experience with the code, then, and merge if I get multiple thumbs-up and no objections.

**Comment by danmichaelo** [comment]
:+1: Sorry for my absence and for introducing the bug, and thanks for the PR! I cannot spot any issues with it, so I will merge right away, and then try to add a test later on.

**Comment by AdamWill** [comment]
does the issue need to be open any longer? seems like the fix works.

I'm working through adding tests to wikitcms and at some point I'll hit my subclasses of the stuff in `listing` and have to figure out how to do tests for those, so if I get there before @danmichaelo I'll probably be able to contribute tests upstream too at that point :P

**Comment by danmichaelo** [comment]
Let's see who gets there first ;)
