### ISSUE TITLE
SSLError 

### ISSUE THREAD

**Issue by carchaias** [mwclient/mwclient#111]
```
import mwclient
site = mwclient.Site('aquanautweb.de', path='/testwiki/')
print site
```
end with this:

```
==== RESTART: C:\Users\ralf.hagenbuck.ZEITGEIST\Desktop\test_mwclient.py ====

Traceback (most recent call last):
  File "C:\Users\XXXX\test_mwclient.py", line 4, in <module>
    site = mwclient.Site('aquanautweb.de', path='/testwiki/')
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 112, in __init__
    self.site_init()
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 120, in site_init
    siprop='general|namespaces', uiprop='groups|rights', retry_on_error=False)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 202, in api
    info = self.raw_api(action, **kwargs)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 307, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 275, in raw_call
    stream = self.connection.post(fullurl, data=data, files=files, headers=headers)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
>>> 
```

It works with https://en.wikipedia.org or other wikipedia pages. The API on my wiki is turned on so I can send requests via the browser.

**Comment by tosher** [comment]
With 
```python
path='/testwiki/api.php?'
```
..and without ssl verification (#105), because of verification was failed (i don't know why).
works fine.

**Comment by danmichaelo** [comment]
Perhaps your site is not set up with SSL? In that case you must use `site = mwclient.Site(('http', 'aquanautweb.de'), path='/testwiki/')`. We moved to https as default in version 0.8.0.

**Comment by tosher** [comment]
Will be useful for wikipedia like configuration (api path, etc.):
https://www.mediawiki.org/wiki/Manual:Short_URL

**Comment by carchaias** [comment]
> It could be related to the case that your server does not provide the intermediate certificate:

Well, the linked services say so. On the server itself I can't see any problem. The chain seems to be in proper state and all current browsers have no problem to establish a TLS connection. 

> ..and without ssl verification (#105), because of verification was failed (i don't know why),
works fine.
I don't understand #105. The server enforces https for the site.

**Comment by tosher** [comment]
With changes of #105, we can to create the connection without ssl certificate validation:
```python
sitecon = mwclient.Site(host=host, path=path, verify=False)
```

**Comment by carchaias** [comment]
No?!?
`import mwclient

site = mwclient.Site('aquanautweb.de', path='/testwiki/', verify=False)
print site`

```
==== RESTART: C:\xxxxx\test_mwclient.py ====

Traceback (most recent call last):
  File "C:\xxxxx\test_mwclient.py", line 4, in <module>
    site = mwclient.Site('aquanautweb.de', path='/testwiki/', verify=False)
TypeError: __init__() got an unexpected keyword argument 'verify'
>>> 
``

**Comment by tosher** [comment]
This parameter will be available after permitting this [pull request](https://help.github.com/articles/incorporating-changes-from-a-pull-request/).
For tests you can use [fork repository](https://github.com/tosher/mwclient)

**Comment by danmichaelo** [comment]
Sure, but disabling ssl verification is just a workaround. @carchaias I had a missing intermediate certificate on my own server once (not a mediawiki installation) and it also worked in most browsers, but not in Chrome on Android 4 and not with curl from some servers.

To fix it, you need to add the intermediate certificate to your webserver. With nginx I just had to cut and paste the intermediate certificate from my certificate provider into my certificate file if I remember right. Instructions for how to do this with your webserver should be easy to find by googling something like "intermediate certificate + [webserver]".

**Comment by carchaias** [comment]
Well, I was able to complete the intermediate certificate chain by adding an missing cert to the server. The ssl-check- service reports mentioned above reflects this. 
What's bad:
The script itself still doesn't work.

`SSLError: EOF occurred in violation of protocol (_ssl.c:590)`

Any ideas what this 'violation of protokol' can be more precisely.

**Comment by tosher** [comment]
Can you show the final code?

**Comment by carchaias** [comment]
```
import mwclient

site = mwclient.Site('aquanautweb.de', path='/testwiki/')
print site
```
And here is the full output:

`==== RESTART: C:\xxxxx\test_mwclient.py ====

Traceback (most recent call last):
  File "C:\xxxxx\test_mwclient.py", line 3, in <module>
    site = mwclient.Site('aquanautweb.de', path='/testwiki/')
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 112, in __init__
    self.site_init()
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 120, in site_init
    siprop='general|namespaces', uiprop='groups|rights', retry_on_error=False)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 202, in api
    info = self.raw_api(action, **kwargs)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 307, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "C:\Python27\lib\site-packages\mwclient\client.py", line 275, in raw_call
    stream = self.connection.post(fullurl, data=data, files=files, headers=headers)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)`

**Comment by danmichaelo** [comment]
Ah, it's because your server only support TLSv1, not TLSv1.1 or TLSv1.2. Seems like `requests` doesn't detect this… The solution on https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/  seems to work:

```python

from requests.adapters import HTTPAdapter
from requests.packages.urllib3.poolmanager import PoolManager
import ssl

class MyAdapter(HTTPAdapter):
    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = PoolManager(num_pools=connections,
                                       maxsize=maxsize,
                                       block=block,
                                       ssl_version=ssl.PROTOCOL_TLSv1)

import requests
session = requests.Session()
session.mount('https://', MyAdapter())

site = Site('aquanautweb.de', path='/testwiki/', pool=session)
```

**Comment by AdamWill** [comment]
you really really should make your server support TLS v1.2.

**Comment by carchaias** [comment]
Hi again,
I see this is closed already, and this is right. It works now. The tip of @danmichaelo was right. Thanks for helping so much with this issue that at least was not part of mwclient. We will have a new operating system on the server soon that will support TLS 1.2...
