### ISSUE TITLE
Sections and subsections treated differently, is this API or mwclient?

### ISSUE THREAD

**Issue by billcarlson** [mwclient/mwclient#112]
Seeing issue when using page.text(section=x)

Consider following page:
```
== Section 1 ==
stuff

=== Subsection 1 ===
sub stuff

== Section 2 ==
stuff stuff
```

page.text(section=1) is
```
== Section 1 ==
stuff

=== Subsection 1 ===
sub stuff
```

page.text(section=2) is
```
=== Subsection 1 ===
sub stuff
```

Why is asking for section=1 including section=2?

Is this mwclient code issue or Mediawiki API problem?

Info: mwclient 0.8.1, python 2.6.6, Mediawiki 1.23

Considering how TOC is presented by Mediawiki, it makes sense to use floats, so sections are 1, 1.1 and 2.

**Comment by PierreSelim** [comment]
This is how the MediaWiki API works.

For example <https://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles=Paris&rvprop=timestamp|user|comment|content&rvsection=1> will fetch section 1 of article Paris on English Wikipedia, i.e. content from the following sections and subsections
```
== History ==
=== Etymology ===
=== Origins ===
=== Middle Ages to Louis XIV ===
=== The 18th and 19th century ===
=== 20th and 21st century ===
```
Whereas <https://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles=Paris&rvprop=timestamp|user|comment|content&rvsection=1> will fetch only section 2 of the very same article i.e. `=== Etymology ===`

It looks like mwclient works the same way than the API which is probably a good thing.

**Comment by danmichaelo** [comment]
True, it's a MediaWiki thing.. I think it would be confusing to make a custom implementation in mwclient. 

But note that you can get helpful TOC information from `prop=sections`, including 

```python
mwclient.Site('en.wikipedia.org').raw_api('parse', page='Paris', prop='sections')
```

```json
{
   "parse": {
      "sections": [
         {
            "index": "1", 
            "level": "2", 
            "fromtitle": "Paris", 
            "toclevel": 1, 
            "number": "1", 
            "byteoffset": 9323, 
            "line": "History", 
            "anchor": "History"
         }, 
         {
            "index": "2", 
            "level": "3", 
            "fromtitle": "Paris", 
            "toclevel": 2, 
            "number": "1.1", 
            "byteoffset": 9380, 
            "line": "Etymology", 
            "anchor": "Etymology"
         }, 
         {
            "index": "3", 
            "level": "3", 
            "fromtitle": "Paris", 
            "toclevel": 2, 
            "number": "1.2", 
            "byteoffset": 10844, 
            "line": "Origins", 
            "anchor": "Origins"
         }, 
  ………
}
```

Perhaps we should add a `sections()` method on the `Page` object to simplify getting that information?

**Comment by billcarlson** [comment]
That the variable "level" is there and really is the correct numbering suggests that for the API changing "section" was considered unchangeable in behavior.

I've filed a request to consider making level available in edit in the Mediawiki API:
https://phabricator.wikimedia.org/T127619

**Comment by danmichaelo** [comment]
Good. But are you sure it's `level` you want, not `number` (like `"1.2"`)?

**Comment by billcarlson** [comment]
Doh! Yes, I meant number, my mistake.

**Comment by danmichaelo** [comment]
Closing this issue. Feel free to open a new issue if you have ideas on how mwclient could make it easier to work with sections without breaking api compability. As mentioned, I'm considering adding `.sections()` to `Page`.
