### ISSUE TITLE
OAuth login

### ISSUE THREAD

**Issue by Steinsplitter** [mwclient/mwclient#115]
Add support to allow login via secured oauth token.

**Comment by scholer** [comment]
Would love to see this. Right now our users log in using Chrome, then we extract/hijack the session id cookie from chrome's cookie database and inject it with the headers. While this works, it is a bit "hacky", and may break whenever Chrome decides to change its sqlite schema and/or file locations. :-/

**Comment by danmichaelo** [comment]
Should be supported now: http://mwclient.readthedocs.io/en/latest/user/connecting.html#oauth

**Comment by zhuyifei1999** [comment]
Can this feature be added to [ConfiguredSite](https://github.com/mwclient/mwclient/blob/master/mwclient/ex.py#L40) as well?
