### ISSUE TITLE
Page properties 

### ISSUE THREAD

**Issue by rjsbhatia** [mwclient/mwclient#117]
Looking at Page.py, particularly this section (line 48-):

```
        self.protection = dict([(i['type'], (i['level'], i['expiry'])) for i in info.get('protection', ()) if i])
        self.redirect = 'redirect' in info
        self.pageid = info.get('pageid', None)
        self.contentmodel = info.get('contentmodel', None)
        self.pagelanguage = info.get('pagelanguage', None)
        self.restrictiontypes = info.get('restrictiontypes', None)

        self.last_rev_time = None
```

if i access page.redirect or anything before it, it works, but I get an error for the next few attributes
AttributeError: 'Page' object has no attribute 'pageid'
AttributeError: 'Page' object has no attribute 'contentmodel'
AttributeError: 'Page' object has no attribute 'pagelanguage'
..
and I get last_rev_time = None. 

I am getting these page objects from site.allpages()

I need pageid, title and revision info. If i use query i can't get revisions, and if i use the allpages iterator I can't seem to get pageids. I know I can use them both together and i will have all the information. 

rjs

**Comment by danmichaelo** [comment]
Can you please add a small code example I can use to reproduce this? You should be able to get pageids from allpages.

**Comment by rjsbhatia** [comment]
Hi Dan,

Thanks for the quick response. Here is  a generic version  of my code that ends up with the same issue. 

`    site = mwclient.Site('en.wikipedia.org')
    for page in site.allpages(filterredir='nonredirects'):
        print page.name
        print page.revision
        print page.pageid
`

And this is what I get:
"Mad" Mike Whiddett
709283489
and for
print page.pageid
AttributeError: 'Page' object has no attribute 'pageid'

**Comment by danmichaelo** [comment]
Strange, I can't reproduce that, it works for me. Could you try

```python
print mwclient.__ver__
site = mwclient.Site('en.wikipedia.org')
firstpage = next(site.allpages(filterredir='nonredirects'))
print dir(firstpage)
```
? Here's what I get:
```
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', '_info', '_textcache', 'backlinks', 'can', 'categories', 'contentmodel', 'delete', 'edit', 'edit_time', 'embeddedin', 'exists', 'extlinks', 'get_expanded', 'get_token', 'handle_edit_error', 'images', 'iwlinks', 'langlinks', 'last_rev_time', 'length', 'links', 'move', 'name', 'namespace', 'normalize_title', 'page_title', 'pageid', 'pagelanguage', 'protection', 'purge', 'redirect', 'redirects_to', 'resolve_redirect', 'restrictiontypes', 'revision', 'revisions', 'save', 'site', 'strip_namespace', 'templates', 'text', 'touched']
```

**Comment by rjsbhatia** [comment]
I was using an older version. 
0.7.2.dev1
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', '__weakref__', '_info', 'backlinks', 'can', 'categories', 'delete', 'edit', 'edit_time', 'embeddedin', 'exists', 'extlinks', 'get_expanded', 'get_token', 'handle_edit_error', 'images', 'iwlinks', 'langlinks', 'last_rev_time', 'length', 'links', 'move', 'name', 'namespace', 'normalize_title', 'page_title', 'protection', 'purge', 'redirect', 'redirects_to', 'resolve_redirect', 'revision', 'revisions', 'save', 'section', 'site', 'strip_namespace', 'templates', 'text', 'touched']

i updated to 0.8.1 and it works now. 
Thanks for your help! Sorry it turned out to be a version issue.

**Comment by danmichaelo** [comment]
Good you got it working!
