### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#120]
https://travis-ci.org/mwclient/mwclient/jobs/128559531

because of https://github.com/aliles/funcsigs/issues/28

**Comment by danmichaelo** [comment]
Dependency on funcsigs was added in 3c472e32daac5671dd2b6ee5eab5e7813feac078 . Perhaps we don't need it anymore?

**Comment by PierreSelim** [comment]
Seems better now, which makes the CI useful again. Thanks :+1:
