### ISSUE TITLE
Sign the python3 pledge

### ISSUE THREAD

**Issue by waldyrious** [mwclient/mwclient#124]
https://python3statement.github.io

**Comment by danmichaelo** [comment]
Good to see the initiative, but our small project isn't going to be an influencer, so I'm not sure if it's needed?

**Comment by waldyrious** [comment]
Good point. I don't recall how the page looked when I first suggested this, but looking at it today, indeed it looks like adding too many small projects would add a lot of visual noise without much benefit to the message. Let's close this.
