### ISSUE TITLE
Update txt files to markdown

### ISSUE THREAD

**Issue by waldyrious** [mwclient/mwclient#13]
Especially README

**Comment by waldyrious** [comment]
Relevant note from https://github.com/pypa/packaging-problems/issues/46#issuecomment-373913112:

> To clarify, Markdown readme detection isn't automatic: you need to follow the instructions for and reupload your project.

**Comment by danmichaelo** [comment]
Just tested markdown with another project and it works 🎉  https://pypi.org/project/slipsomat/

Just had to set `long_description_content_type='text/markdown'` in `setup.py`:

https://github.com/scriptotek/alma-slipsomat/commit/a85eca932ab7353e8ca3c40d2e79b0ba38a62d1f#diff-2eeaed663bd0d25b7e608891384b7298R23

**Comment by waldyrious** [comment]
@danmichaelo that's great to hear! Can I convert the README back to markdown, then?

**Comment by danmichaelo** [comment]
@waldyrious Absolutely :)

**Comment by waldyrious** [comment]
Fixed with the merging of #192 :smile: :tada:
