### ISSUE TITLE
Release v0.8.2 with OAuth support

### ISSUE THREAD

**Issue by bd808** [mwclient/mwclient#141]
I would like to use this library as part of the Tool Labs admin console (<https://toolsadmin.wikimedia.org/>) to automate various Wikitech actions. My use case requires authentication and I would like to use OAuth rather than username+password authentication. It would be much easier for me to deploy the library on Wikimedia's production servers from PyPi than via a GitHub hash.

**Comment by danmichaelo** [comment]
True, it's way too long since the last release. I'll ship 0.8.2 on Saturday (or earlier if I happen to be in the mood some afternoon :))

**Comment by danmichaelo** [comment]
Done 🚀
