### ISSUE TITLE
suggestion: rename RELEASE-NOTES.md

### ISSUE THREAD

**Issue by waldyrious** [mwclient/mwclient#142]
...to VERSIONS.md or CHANGELOG.md (or something alike). Otherwise it may not be clear that it includes data for releases other than the current one.

Any thoughts/suggestions?

**Comment by danmichaelo** [comment]
Perhaps, but we shouldn't just remove it altogether, per #109 ?

**Comment by waldyrious** [comment]
Indeed. I really have to just go ahead and do that. I wouldn't remove the file altogether; we should keep it, with a link to the github releases page.
