### ISSUE TITLE
Contributing to Documentation

### ISSUE THREAD

**Issue by andrecastro0o** [mwclient/mwclient#144]
Hi. Anyway I could contribute to mwclient documentation?
I found that the github wiki is out dated for v.0.8.2 and the current documentation is in https://media.readthedocs.org/pdf/mwclient/latest/mwclient.pdf

I have some additions, such as connecting to mw site with http and path, which is not featured in the documentation `mwclient.Site( ("http", "beyond-social.org") , path="/wiki/")`

best
a

**Comment by waldyrious** [comment]
@andrecastro0o thanks for your interest! I'm a bit swamped with work right now, but I will answer in proper detail this weekend.

**Comment by andrecastro0o** [comment]
no worries. It was just that addition. As mwclient was trowing errors after I upgraded, simply because the http wasn't there.
And in the documentation I could not find anywhere where the case of using http and a path was contemplated.
Thanks for the great library!!!

**Comment by waldyrious** [comment]
@andrecastro0o please reopen the issue nevertheless, since the documentation does need some work, including moving some of the wiki content into docstrings in the code itself, and currently there aren't clear guidelines on how people can contribute to that effect.

**Comment by andrecastro0o** [comment]
Sure. Let me know if I can help.

**Comment by danmichaelo** [comment]
Thanks for the interest in improving the document @andrecastro0o !

I think what you mentioned is already covered at http://mwclient.readthedocs.io/en/latest/user/connecting.html ?

In any case, the source files for the user guide is located under https://github.com/mwclient/mwclient/tree/master/docs/source

It's quite incomplete, so any improvements are most welcome :)
