### ISSUE TITLE
mwclient broken with mediawiki 1.27 + ?

### ISSUE THREAD

**Issue by ubibene** [mwclient/mwclient#148]
Hi,

I wrote a script to edit some pages on my MW Wiki . All was working fine with Mediawiki 1.26.

I upgraded to MW 1.28.1 and the script is failing when creating the site object (using mwclient 0.8.4) :

` site=mwclient.Site(('http',mywikiurl),'/')

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 124, in __init__
    self.site_init()

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 146, in site_init
    retry_on_error=False)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 228, in get
    return self.api(action, 'GET', *args, **kwargs)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 279, in api
    info = self.raw_api(action, http_method, **kwargs)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 398, in raw_api
    http_method=http_method)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 369, in raw_call
    stream.raise_for_status()

  File "/usr/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://mywikiurl/api.php?format=json&continue=&meta=siteinfo%7Cuserinfo%7Cuserinfo&action=query&siprop=general%7Cnamespaces&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg

`
Although the error message says there is a 404 error , the url exists and the page content is : 

`{"error":{"code":"readapidenied","info":"You need read permission to use this module","*":"See http://mywikiurl/api.php for API usage"}}`

It seems the API  permission mechanism has changed since MW 1.27 which introduced bot passwords : https://www.mediawiki.org/wiki/Manual:Bot_passwords

What I tried so far : 

- call Site and add 'do_init=False'  `site=mwclient.Site(('http',mywikiurl),'/',do_init=False)`
- then try to login : site.login(login,password)

I both used : 
- a (login, password) of an account marked as a bot in the wiki
- a "botpassword" linked to a regular account

Both login methods are failing : 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 488, in login
    login = self.post('login', **kwargs)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 239, in post
    return self.api(action, 'POST', *args, **kwargs)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 279, in api
    info = self.raw_api(action, http_method, **kwargs)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 398, in raw_api
    http_method=http_method)

  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 369, in raw_call
    stream.raise_for_status()

  File "/usr/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://lmywikiurl/api.php
`

Any ideas ? 

Thanks !

**Comment by ubibene** [comment]
See also  :  https://www.mediawiki.org/wiki/API:Login/en

> As of MediaWiki 1.27, there are two API actions used to authenticate: login and clientlogin.

>Bots and other non-interactive applications should generally use owner-only OAuth consumers when available to authenticate as it is more secure, however bot passwords can be used with the login action as described on this page.

>Interactive applications such as custom editors or patrolling applications that provide a service without intending to fully replace the website should generally also use OAuth for authenticating the tool, as it is easier and more secure, however the clientlogin action can be used if that is unavailable.

>Interactive applications such as mobile apps that aim to completely replace access to the web-based user interface should use the clientlogin action to authenticate.

**Comment by ubibene** [comment]
To continue the above comment

at https://www.mediawiki.org/wiki/API:Login/en

> In MediaWiki versions before 1.27, only the login action is available and should be used by all clients needing to login. As of 1.27, the login action should only be used in combination with bot passwords, and clientlogin should be used by interactive applications.

So if mwclient wants to login it has to use a login with a bot password which must be created on the wiki site (MW 1.27+)

> To successfully log in, a login token must first be retrieved. In MediaWiki 1.27 and later, this token should be fetched using a tokens query with type=login. For older versions, a POST to the login action is required instead.

In client.py / def login(...) from line 487 on :

`
487             while True:

488                 login = self.post('login', **kwargs)

489                 if login['login']['result'] == 'Success':

490                     break

491                 elif login['login']['result'] == 'NeedToken':

492                     kwargs['lgtoken'] = login['login']['token']

493                 elif login['login']['result'] == 'Throttled':

494                     sleeper.sleep(int(login['login'].get('wait', 5)))

495                 else:

496                     raise errors.LoginError(self, login['login'])

`

So maybe line 488 should be changed to call a query tokens ( https://www.mediawiki.org/wiki/API:Tokens ) ?

**Comment by PierreSelim** [comment]
I cannot reproduce your bug.
I just installed in a fresh python 3.6 virtualenv mwclient (and ipython).

```
In [3]: import mwclient

In [4]: site = mwclient.Site('www.mediawiki.org')

In [5]: site.login(login, passwd)

In [7]: mwclient.__ver__
Out[7]: '0.8.4'

In [8]: site.version
Out[8]: (1, 29, 0, '-wmf', 21)
```
Can you check which version of mwclient you are using with `mwclient.__ver__` and wich version you're site is running on with `site.version` (without login actions)

**Comment by ubibene** [comment]
Hi

mwclient.__ver__ is 0.8.4

My mediawiki instance has version 1.28.1 ( I cannot access site.version as an exception is raised when instanciating the site object)

My wiki is read protected, that is users have to log in before accessing the wiki pages

My python version is 2.7.5

**Comment by danmichaelo** [comment]
The old way of getting a login token still works again WMF wikis (tested just now), but we could test the new way. I'll see if I can prepare a patch for testing later today.

Anyways, it's strange that you get a 404...

**Comment by ubibene** [comment]
Hummm, 

I must have a configuration problem somewhere . 

Calling site with the dns name in the url  fails , but succeeds with the ip address

> site2 = mwclient.Site(("http","myurlxxx"),"/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 124, in __init__
    self.site_init()
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 146, in site_init
    retry_on_error=False)
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 228, in get
    return self.api(action, 'GET', *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 279, in api
    info = self.raw_api(action, http_method, **kwargs)
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 398, in raw_api
    http_method=http_method)
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 369, in raw_call
    stream.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://myurlxxx/api.php?format=json&continue=&meta=siteinfo%7Cuserinfo%7Cuserinfo&action=query&siprop=general%7Cnamespaces&uiprop=groups%7Crights%7Cblockinfo%7Chasmsg

> site=mwclient.Site(("http","10.117.xxx"),"/")
no error message
>  page = site.pages['Accueil']
> page.text()
is working ...

So the root cause seems indeed  to be the 404 error when using named url ...

**Comment by ubibene** [comment]
OK, sorry for the inconvenience :  the named url is not resolved by the dns server called from the machine where the script is executed. This is why the script is failing. 

You can close the ticket. 

Have a nice weekend.

**Comment by danmichaelo** [comment]
You too, glad you found the problem! In any case, it's good to be reminded about the new login token mechanism.
