### ISSUE TITLE
Fetch login token using a tokens query with type=login for MW >= 1.27

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#149]
MediaWiki 1.27 introduced a new way of fetching the login token:

https://www.mediawiki.org/wiki/API:Login/en#The_login_action

http://mediawiki-api.wikimedia.narkive.com/TFtAhmtK/mediawiki-api-announce-changes-and-deprecation-in-login-and-createaccount-tokens

**Comment by ubibene** [comment]
Hi

having resolving my 404 error problems, If  I try to connect to my read-protected access mediawiki instance (1.28.1) :  


```
import mwclient
site=mwclient.Site(('http','myurl'),'/')
site.login(mylogin,mypasswd)
```

The python interpreter get stuck at the third line.

So I grabbed the latest client.py version (the one you have just modifed)

Calling site.login now raises the following error : 

```
 File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mwclient/client.py", line 485, in login
    if self.version[:2] >= (1, 27):
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Python version is 2.7.5

**Comment by ubibene** [comment]
Commenting out the test on version number does not help

```
485             kwargs['lgtoken'] = self.get_token('login')
486             #if self.version[:2] >= (1, 27):
487             #    kwargs['lgtoken'] = self.get_token('login')
```

because in get_token() : 
```
503     def get_token(self, type, force=False, title=None):
504
505         if self.version[:2] >= (1, 24):
```
line 505 , self.version is accessed but is not yet defined , yielding the same error as above

**Comment by ubibene** [comment]
Is this can help, here is how I can authenticate and login to my wiki


```
import requests
import json


url = 'mywikiurl/api.php'
# get the login token
payload = {'action': 'query','meta':'tokens','type':'login','format':'json'}
r = requests.get(url, params=payload)
p_dict = json.loads(r.text)
logintoken= p_dict["query"]["tokens"]["logintoken"]
# login
myname = 'myusername@mybotname'
mypass='mybotpassword'
payload = {'action': 'login','lgname':myname,'lgpassword':mypass,'lgtoken':logintoken,'format':'json'}
r = requests.post(url, data=payload,cookies=r.cookies)
print (r.text)
print (r.status_code)
```
execution ouput

```
{"login":{"result":"Success","lguserid":1,"lgusername":"myusername"}}
200
```

**Comment by ubibene** [comment]
As a consequence get_token should probably be modified toot because as it is now : 

in def login():
 `kwargs['lgtoken'] = self.get_token('login')`

in get_token():

```
515         if self.tokens.get(type, '0') == '0' or force:
516
517             if self.version[:2] >= (1, 24):
518                 info = self.post('query', meta='tokens', type=type)
519                 self.tokens[type] = info['query']['tokens']['%stoken' % type]
```
line 518 should  probably be when MW >= 1.27  and type=='login" (->get instead of post)

`info = self.get('query', meta='tokens', type=type)`

I tried the above changes but I still have an error when calling site.login because of the following lines in def api() (called by self.get() ...
```

270         if action == 'query':
271             if 'meta' in kwargs:
272                 kwargs['meta'] += '|userinfo'
```
This results in calling 

http://mywikiurl/api.php?action=queryaction=query&meta=tokens&meta=userinfo|&type=login...
instead of 
http://mywikiurl/api.php?action=queryaction=query&meta=tokens&meta=userinfo|&type=login...

the userinfo parameter cause an readapidenied error

**Comment by danmichaelo** [comment]
Thanks for all the info! Is there any way we can detect the mediawiki version from a private wiki? I guess we could just try to make a tokens query (without asking for userinfo) and then fallback to the old login method if that fails..

**Comment by ubibene** [comment]
Hi
I don't think there is.

To get the mediawiki version , one should call  : 

`http://mywiki/api.php?action=query&meta=siteinfo&siprop=general`

But this yield an readapidenied error on a private wiki....

Moreover you can read here ( https://www.mediawiki.org/wiki/API:FAQ/fr#do_I_get_the_readapidenied_error.3F ) 

> Why do I get the readapidenied error?
> 
> The wiki you're querying contains private content and requires users to log in in order to be able to read all pages. This means that a client needs to be logged in to query any information at all through the API. See the quick start guide for more information. **It's not currently possible to query the contents of whitelisted pages without logging in, even though they're available in the regular user interface**.

So whitelisting the url api.php?action=query&meta=siteinfo&siprop=general is not an option either.

>  I guess we could just try to make a tokens query (without asking for userinfo) and then fallback to the old login method if that fails..

Yep, that sounds good

**Comment by ubibene** [comment]
For the record : 

http://mywiki/api.php?action=query&meta=tokens&type=login&format=json

yields on  MW 1.28.1
`{"batchcomplete":"","query":{"tokens":{"logintoken":"5b774e4285b469619789e94xxxxxxxxxxxxxxxx+\\"}}}`
and on MW 1.26 (pre 1.27) :
`{"batchcomplete":"","warnings":{"tokens":{"*":"Unrecognized value for parameter 'type': login"}},"query":{"tokens":{}}}`

**Comment by ubibene** [comment]
By the way, MW 1.23 LTS support ends this month https://www.mediawiki.org/wiki/Version_lifecycle/en#Versions_and_their_end-of-life


MW 1.24 to MW 1.26 are no more maintained
![mw](https://cloud.githubusercontent.com/assets/16741615/25694338/7519ee2e-30ae-11e7-9a98-92ba24c78bd8.png)


The next LTS version is MW 1.27.x 

May be you'll have to drop support of  MW <= 1.27 in mwclient

**Comment by ubibene** [comment]
Hello
strange : I cannot login on a private MW wiki (1.26) with mwclient 0.8.5 ( readapidenied error).  login is OK for a MW 1.27.3 private wiki.

**Comment by danmichaelo** [comment]
Ouch. Could you post the traceback? I wonder if's related to the token fetching on line 502 or the post login on 507..

**Comment by danmichaelo** [comment]
I don't have a wiki to test with, could you test if this throws a readapidenied?

```
site = Site('HOST', do_init=False)
site.raw_api('query', 'GET', meta='tokens', type='login')
```

**Comment by ubibene** [comment]
Yep, I'll do it next week when I'll be back at the office. MB.

**Comment by ubibene** [comment]
Hi

> Ouch. Could you post the traceback? I wonder if's related to the token fetching on line 502 or the post login on 507..

```

 File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 502, in login
  File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 539, in get_token
  File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 316, in handle_api_result
mwclient.errors.APIError: (u'readapidenied', u'You need read permission to use this module', u'See http://xxxx/api.php for API usage')
```

> site = Site('HOST', do_init=False)
> site.raw_api('query', 'GET', meta='tokens', type='login')

The interpreter just hangs

**Comment by danmichaelo** [comment]
How about

    site.raw_api('query', 'GET', meta='tokens', type='login', retry_on_error=False)

?

**Comment by ubibene** [comment]
`{u'error': {u'info': u'You need read permission to use this module', u'*': u'See http://xxx/api.php for API usage', u'code': u'readapidenied'}}`

**Comment by ubibene** [comment]
But

 `site.raw_api('login', 'POST', lgname='myncame',retry_on_error=False)`

gives

{u'login': {u'cookieprefix': u'mediawiki', u'token': u'463a69a8d39bxxxxxxxxxxxxxxxxxxxxxxxx', u'sessionid': u'aea951ff4a4de839780dxxxxxxxxxxxxxxx', u'result': u'NeedToken'}}

**Comment by danmichaelo** [comment]
Right, so the problem is that it keeps retrying the `meta=tokens` call. What we want is that it should try `meta=tokens` once, and if it fails proceed immediately to try the POST call.

The strange part is that it only keeps retrying if it gets an error response with status in the 5XX range, but in this case I would expect something like https://httpstatuses.com/401

Could you try

    import logging
    logging.basicConfig(level=logging.WARNING)
    from mwclient import Site
    ...

and then the rest of the login. You should now see a message like "Received {status} response: {text}. Retrying in a moment.". What i'm interested in is the status code.

**Comment by ubibene** [comment]
Well I'm confused, I can login this morning !

```
Python 3.4.5 (default, Nov  9 2016, 16:24:59)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import mwclient
>>> site = mwclient.Site(("http","myurl"),"/")
>>> site.login("myuser","mypass")
>>> site.version
(1, 26, 3)
```

**Comment by ubibene** [comment]
Made some tests again this afternoon and cannot reproduce the "bug".  You may close the issue if you like.

**Comment by danmichaelo** [comment]
Ok, let me know if it happens again
