### ISSUE TITLE
Client.ask() fails if there is no anwser to the semantic query. or if the query is malformed

### ISSUE THREAD

**Issue by ubibene** [mwclient/mwclient#161]
Damned !

In Client.ask()
```
results = self.raw_api('ask', query='{query}|offset={offset}'.format(
                query=query, offset=offset), http_method='GET', **kwargs)

            offset = results.get('query-continue-offset')
            for key, value in results['query']['results'].iteritems():
                yield {key: value}
```
If the semantic query gets results:
-  results['query ']['results'] is a dictionnary holding the answers , 
- otherwise it is an empty list and results['query']['results'].iteritems() breaks ( AttributeError: 'list' object has no attribute 'iteritems' )

My mistake. 

I'll look into it,

**Comment by danmichaelo** [comment]
Note: I updated the generator to not yield an empty dictionary if there's zero results. To check if there's zero results, it's better to count the number of results you get from the generator

    answers = site.ask('..')
    num_answers = len(list(answers))

**Comment by ubibene** [comment]
Thanks, it's cleaner that way. I'll post a message to the SMW user list about it.
