### ISSUE TITLE
Site.pages fails while opening Unicode text in URL

### ISSUE THREAD

**Issue by msj2** [mwclient/mwclient#169]
import mwclient
from mwclient import Site
site = mwclient.Site('kn.wikisource.org')

I tried to open the url from Chrome, which has non-English Font, 

i.e., any of the 3 below....
page = site.pages['ಛಲ_ಬೇಕು_ಶರಣಂಗೆ']
page = site.pages['ಛಲ_ಬೇಕು_ಶರಣಂಗೆ'].encode('utf-8')
page = site.pages['ಛಲ_ಬೇಕು_ಶರಣಂಗೆ'].encode('utf-16')
I get error.
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)

However, if I copy the URL from Chrome, paste it into GEDIT, which converts it into below format
https://kn.wikisource.org/wiki/%E0%B2%9B%E0%B2%B2_%E0%B2%AC%E0%B3%87%E0%B2%95%E0%B3%81_%E0%B2%B6%E0%B2%B0%E0%B2%A3%E0%B2%82%E0%B2%97%E0%B3%86 
using the below.

& invoke site.pages  It works fine.

Help me to get this site.pages['ಛಲ_ಬೇಕು_ಶರಣಂಗೆ'] working...

**Comment by msj2** [comment]
wondering if there is a way to convert the non-English URL

https://kn.wikisource.org/wiki/ಛಲ_ಬೇಕು_ಶರಣಂಗೆ

into 
https://kn.wikisource.org/wiki/%E0%B2%9B%E0%B2%B2_%E0%B2%AC%E0%B3%87%E0%B2%95%E0%B3%81_%E0%B2%B6%E0%B2%B0%E0%B2%A3%E0%B2%82%E0%B2%97%E0%B3%86

It'll be much helpful to me.

**Comment by danmichaelo** [comment]
Should work on Python 3. On Python 2 it should also work if you use unicode strings like so:

    page = site.pages[u'ಛಲ_ಬೇಕು_ಶರಣಂಗೆ']

**Comment by danmichaelo** [comment]
In general I think Unicode support in mwclient itself should be good, but on Python 2 you have to be a bit careful with input and output.

**Comment by msj2** [comment]
Terrific, I raise an issue & sleep. You've answered within an hour. 
Absolutely Terrific Thank you.

**Comment by PierreSelim** [comment]
I think we can close the issue ?
