### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by andrecastro0o** [mwclient/mwclient#176]
I am having a hard time interfacing the a wiki api via  mwclient

The api is in https://aa.xpub.nl/api.php

```python 
Site('aa.xpub.nl', '/')

returns:
SSLError: hostname 'aa.xpub.nl' doesn't match either of 'dump.xpub.nl',
'flyer.xpub.nl', 'git.xpub.nl', 'issue.xpub.nl', 'sp.xpub.nl',
'todo.xpub.nl', 'www.xpub.nl', 'xpub.nl'
```

And so does Site(('http','aa.xpub.nl'), '/') or
Site(('https','aa.xpub.nl'), '/')

It is likely because the subdomain hasnt been added to the SSL cert of the domain, so the SSL python library
 refuses to connect.

do you folks have any quick fixes for this error?
Much appreciated
a

**Comment by danmichaelo** [comment]
The cert should really be fixed. But quick fix could be something like:

```
from requests.sessions import Session
session = Session()
```
... google how to configure a requests session to not verify certificates …
```
site = Site('aa.xpub.nl', '/', pool=session, ...)
```

**Comment by devcorrelator** [comment]
So, there is no real direct way to pass on settings/variables to the session class. In my case, my testing involves a server with a self signed cert. I was able to pass 'verify=False' like this:

```
    site = mwclient.Site('example.com', do_init=False)
    site.connection.verify = False
    site.site_init()

```

**Comment by danmichaelo** [comment]
You could also get a free SSL certificate from Let's Encrypt ;)

**Comment by devcorrelator** [comment]
True. I'm my current situation that would be doable; however, I have found myself in situations where that wouldn't be possible. Plus when you're talking internally from one server to another, and no exposure to the wild internet, you can reliably trust the integrity of the self signed cert.
