### ISSUE TITLE
Only providing release notes via github is fragile

### ISSUE THREAD

**Issue by AdamWill** [mwclient/mwclient#178]
This isn't really a code issue, but thought I'd register it somehow. I'm a bit concerned about the approach of only providing release notes via github - not having them actually in the codebase anywhere.

It's nice and convenient now, but what when Github-Skynet goes rogue in 2030 and you want to move to a different provider; are you gonna be able to get all those release notes *out*? What when future historians are reconstructing the events of the Great Wikipedia Meltdown of 2020 which triggered the destruction of the first internet, and they've got a series of mwclient tarballs, but no-one's been able to access any data from Github since the angry mob torched all the servers?

OK, my examples are a bit humorous, but hopefully you get the point ;) Metadata / information that's part of the codebase itself is quite easily preserved, moved around, and rediscovered in future. Metadata / information that's captive inside a third party hosted service...is not.

**Comment by AdamWill** [comment]
(also captive inside github: this issue! sigh.)

**Comment by danmichaelo** [comment]
Perhaps you could copy these comments to #109 and we can close this issue? I agree in principle, but it's quite tedious to maintain the file and mwclient is probably not a historically important library after all :)

**Comment by AdamWill** [comment]
Welp, my degree's in history, and I can say for sure that there's a lot of information we wish we had now that was thrown away at the time because no-one thought it was interesting or important :P but sure. thanks for the pointer to #109 .
