### ISSUE TITLE
 Make pytest-runner a conditional requirement 

### ISSUE THREAD

**Issue by yegorich** [mwclient/mwclient#179]
Having pytest-runner in setup_requires breaks mwclient build in Buildroot. Could you take similar approach as pytablewriter (https://github.com/thombashi/pytablewriter/commit/63fe493b73437b734e00af68bec1c3bb4407168e#diff-2eeaed663bd0d25b7e608891384b7298)

**Comment by danmichaelo** [comment]
Thanks for the PR! Let me know if you need a new release, otherwise I'll wait with that until another change or two are in.

**Comment by yegorich** [comment]
@danmichaelo thanks for applying the fix. No need to hurry with the release. We've applied the patch locally and will remove it as soon as new release will appear.
