### ISSUE TITLE
Invalid page title returns a page where page.exists == True

### ISSUE THREAD

**Issue by automatist** [mwclient/mwclient#183]
I've encountered what seems an odd edge case, namely that if I use site.pages to retrieve a page with a title that contains square brackets, I receive a page object that seems to exist (rather than throwing an Exception as I would prefer / expect).

Example:
p = site.pages["[foo]"]
assert (p.exists == True)

**Comment by danmichaelo** [comment]
Good catch! I first fixed it just so p.exists would be False, but then changed my mind and added an exception.
