### ISSUE TITLE
Support chunked uploads

### ISSUE THREAD

**Issue by chicocvenancio** [mwclient/mwclient#189]
Commons has a 100mb limit for a single request but a 4GB limit for file size. Sending the upload in chunks allows for files bigger than 100mb to be sent.

**Comment by danmichaelo** [comment]
Agree this should definitely be supported. Did a quick implementation here https://github.com/mwclient/mwclient/tree/feat-chunk-upload . Feel free to test it. Will merge it in a few days.

**Comment by chicocvenancio** [comment]
Thanks for the quick development, the code looks good to me. Abuse filter and duplicates finder stopped me from actually creating the files in test.wikipedia.org but the warnings indicate the file did get there...

**Comment by danmichaelo** [comment]
(This was merged a long time ago, so time to close the issue)
