### ISSUE TITLE
Guidance on parsing and cleaning

### ISSUE THREAD

**Issue by richielo** [mwclient/mwclient#191]
Hello,

I am new to this and would like to extract plain text from the text returned by Page.text(). Any idea how can I do that? Sorry for my ignorance and thank you very much for your help in advance.

**Comment by danmichaelo** [comment]
You could try passing it through https://github.com/danmichaelo/mwtextextractor , a small project I made some time ago for that purpose.

Alternatively, you could perhaps use the https://www.mediawiki.org/wiki/API:Parsing_wikitext (Site.parse) and find some other library to strip away the resulting HTML.

**Comment by richielo** [comment]
Thanks! I will give them a try
