### ISSUE TITLE
Ignore SSL Certificate

### ISSUE THREAD

**Issue by lgonzalezsa** [mwclient/mwclient#196]
Hello All,

Could be possible to define site connection but ignoring the SSL certificate?
I am using internal mediawiki and I would like to skip SSL certificate verification for testing purposes.

`site = mwclient.Site(host='hpedia.osp.hpe.com', verify=False)`

I am using mwclient-0.9.1 oauthlib-2.1.0 requests-oauthlib-1.0.0

**Comment by danmichaelo** [comment]
It's possible. Unfortunately, it's not so intuitive how to do it:

    site = mwclient.Site(host='hpedia.osp.hpe.com', reqs={'verify': False})

Reminds me that this was brought up in #119 , will create a new issue for it.
