### ISSUE TITLE
Rename reqs to something more intuitive

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#197]
The option was introduced in  #105 and renamed in  #119, but the name `reqs` is not very intuitive, so I suggest deprecating `reqs` in favour of something better (`connection_kwargs`?). Suggestions are welcome.

**Comment by mitar** [comment]
Maybe `connection_options`?

**Comment by AdamWill** [comment]
@RheingoldRiver replying to https://github.com/mwclient/mwclient/issues/284#issuecomment-2143531881 - I'm not sure about `**kwargs`, personally, dunno what @marcfrederick thinks...I'm working on a PR to rename it to `connection_options`, but I'm not tied to that approach.

**Comment by AdamWill** [comment]
Fixed by https://github.com/mwclient/mwclient/pull/335 .
