### ISSUE TITLE
MW API warnings (verbose & annoying)

### ISSUE THREAD

**Issue by fredzannarbor** [mwclient/mwclient#199]
> WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.
> 
> WARNING:mwclient.client:Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.

Can we make these go away?

**Comment by danmichaelo** [comment]
Ah, yes, thanks for reminding me, it was announced in August:

https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2018-August/000140.html

I'll try to update mwclient this weekend.

**Comment by danmichaelo** [comment]
Updated the `Page.text()` method to get content from the 'main' slot by default. Which means you can continue to use mwclient as before. Content from other slots can be retrieved using the `slot` parameter.

The `action=edit` API doesn't seem to support a slot parameter yet, so I'll have to wait for that.

https://www.mediawiki.org/wiki/Multi-Content_Revisions/Action_API

**Comment by danmichaelo** [comment]
Btw. it's included in version 0.9.2, which is on pypi now.
