### ISSUE TITLE
Use timeout in requests

### ISSUE THREAD

**Issue by binarytrout** [mwclient/mwclient#200]
From the requests docs: http://docs.python-requests.org/en/master/user/quickstart/#timeouts
You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. **Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely**

I propose adding a parameter 'timeout' to Site.raw_call() and passing it on to connection.get() and connection.post()

**Comment by danmichaelo** [comment]
Yeah, that makes sense! What's a good default value? 30 secs?

**Comment by danmichaelo** [comment]
Added it to `Site.requests` instead, which holds the default requests params. This should make it easier to modify.

**Comment by binarytrout** [comment]
Awesome, thanks. Yes I think 30s is probably a good default.
