### ISSUE TITLE
How do search for page titles matching key string?

### ISSUE THREAD

**Issue by fredzannarbor** [mwclient/mwclient#203]
Hi,

I don't understand how to search for page titles matching or fuzzily matching key phrases.  I understand how to use site.pages 

`page = site.pages['Paella']`

but I am stuck trying to search for all the page titles that match or almost match a phrase that has multiple matches, e.g. 'Neil Armstrong'.

**Comment by danmichaelo** [comment]
Hi, see [Site.search](https://mwclient.readthedocs.io/en/master/reference/site.html#mwclient.client.Site.search)
