### ISSUE TITLE
Rename __ver__ to __version__

### ISSUE THREAD

**Issue by pyfisch** [mwclient/mwclient#210]
Follow the [Python Module Version Number convention](https://www.python.org/dev/peps/pep-0396/) and rename `__ver__` to `__version__`. For compatibility `__version__` can be exported as `__ver__`.

**Comment by danmichaelo** [comment]
A PR is welcome. Otherwise, I can fix it at some point.

**Comment by danmichaelo** [comment]
Finally merged, sorry it took so long!
