### ISSUE TITLE
Allow access to site on a http:// URL

### ISSUE THREAD

**Issue by mtausig** [mwclient/mwclient#212]
Currently, the URL scheme used to access the MediaWiki instance is hardcoded to `https` in the `raw_call` function of `client.py`. This makes it impossible to use mwclient wit a wiki which is hosted under an unencrypted http:// URL.

This should be made configurable (either by adding a scheme parameter to the *Site* constructor or by allowing a full URL instead of just the hostname there).

**Comment by mtausig** [comment]
Apologies. I went straight to the reference documentation of the `Site` class and missed this info.

**Comment by waldyrious** [comment]
Wouldn't a specific parameter be a neater way to achieve this, instead of relying on a specific, opaque data structure and the custom code to handle it?

https://github.com/mwclient/mwclient/blob/030cf8aa3b3a7acc9386412461c62049833d612a/mwclient/client.py#L367-L370

This entire bit could be removed if the host and scheme were always assigned individually. That's cleaner both implementation-wise and in terms of a consistent, self-documenting API, no?

**Comment by tosher** [comment]
https://github.com/mwclient/mwclient/pull/198

**Comment by waldyrious** [comment]
Thanks for cross-referencing that PR, @tosher. I think the comment above still stands.

**Comment by danmichaelo** [comment]
> Wouldn't a specific parameter be a neater way to achieve this, instead of relying on a specific, opaque data structure and the custom code to handle it?

I've only kept it for backwards compatibility, but I wouldn't mind if we introduced a new parameter and deprecated the old syntax and then removed it with the next major release or something.

**Comment by waldyrious** [comment]
@danmichaelo shall we reopen #213 then (and this issue as well), provided that it also removes the special handling of the `host` parameter in the code I quoted above?

**Comment by danmichaelo** [comment]
Yup, just re-opened #213. But perhaps keep this issue closed? At least with the current title ("Allow access to site on a http:// URL")

**Comment by mtausig** [comment]
> Yup, just re-opened #213. But perhaps keep this issue closed? At least with the current title ("Allow access to site on a http:// URL")

Better now?
