### ISSUE TITLE
cookiejar increases with every page.save() call resulting in large cookiejar

### ISSUE THREAD

**Issue by tomschulze** [mwclient/mwclient#221]
```py
site = mwclient.Site((config['protocol'], config['url']), path='/')
site.login(config['login'], config['pw'])

pages = ['Test' + str(i) for i in range(100)]

for p in pages:
    page = site.pages[p]
    page.save('Testtext')
```
I use version 0.9.3.

I realized that the cookiejar stored in `site.connection.cookies` incrementally increases with every `page.save()` call. In the example above the 100th call would have a cookiejar with 100 cookies that are sent with the last request. The cookie stored follows this pattern: `('SITENAMEPostEditRevision8461', 'saved')`. I quickly glanced at your code and did not find any hints where these cookies are actually created... I am not too familiar with the mediawiki api.

So when I deploy 6000 pages with the method above, the last request contains 6000 cookies. Am I using your library in the wrong way?

NB:
I tested some template deployment code on a an nginx server which returned a 400 after 192 calls; the server mesage was `client sent too long header line`. I had to add `large_client_header_buffers 4 64k;` to nginx.conf to increase the size a bit. I dont know how other servers respond. I am going to test this afternoon on a apache config.

**Comment by danmichaelo** [comment]
Ouch, see https://phabricator.wikimedia.org/T211233

Mwclient leaves it to the `requests` library to handle cookies. According to [the documentation](https://2.python-requests.org/en/master/api/#api-cookies), it also handles expiration of cookies, but, as mentioned in the phabricator ticket above, it seems like the expiration time is 20 minutes for these cookies, so I guess quite a bit of cookies can pile up in that time.

In the phabricator ticket above, a patch has been submitted, but unfortunately it's not yet merged, so we have to arm ourself with patience I guess: https://gerrit.wikimedia.org/r/c/mediawiki/core/+/477858

Until then, I think a workaround like this should help:

```python
for cookie in site.connection.cookies:
	if cookie.name.startswith('SITENAMEPostEditRevision'):
		site.connection.cookies.clear(cookie.domain, cookie.path, cookie.name)
```

For some reason, I did not see the issue on test.wikipedia.org, so I haven't tested it.

**Comment by tomschulze** [comment]
thanks so much for digging into this and thanks for providing the workaround; feel free to close the issue
