### ISSUE TITLE
urlib3 does not support ipv6

### ISSUE THREAD

**Issue by Callustian** [mwclient/mwclient#222]
Recently using mwclient on Ubuntu18.04. Ipv6 is enabled and Site('') is very slow at a socket connection request.
Disabling ipv6 seems to fix the problem.
Thanks.

**Comment by danmichaelo** [comment]
That's odd :/ mwclient uses the `requests` library for http requests though, so I think this problem is outside the scope of mwclient. Feel free to re-open if you disagree.
