### ISSUE TITLE
Tox doesn't actually run any tests any more

### ISSUE THREAD

**Issue by AdamWill** [mwclient/mwclient#224]
57f716ed removed the `commands` line from `tox.ini`, this one:

    commands=py.test -v --cov --codestyle mwclient test

I'm not sure if this was a mistake or somehow intentional, but the result is that calling `tox` doesn't run the test suite any more. It *only* runs flake8.

**Comment by danmichaelo** [comment]
Definitely a mistake, sorry about that! Thanks for the fix!
