### ISSUE TITLE
Test runs outside of tox don't run flake8, but setup.py claims it's required

### ISSUE THREAD

**Issue by AdamWill** [mwclient/mwclient#226]
57f716ed changed test invocation so that `flake8` is run as a test environment in tox. The `py.test` invocation in tox no longer runs any linter, and `python setup.py test` no longer runs a linter either. But `setup.py` still includes `flake8` in `tests_require`, which is a statement that `python setup.py test` requires it.

The fix for this is *either* to make `python setup.py test` run flake8 *or* to remove the requirement from `tests_require`; I don't know which is preferred.

**Comment by AdamWill** [comment]
BTW, I prefer the latter, linting is distinct from testing and I actually appreciate that they're separate now.

**Comment by danmichaelo** [comment]
Thanks for noticing! Agree that the latter is preferable, so I'm removing flake8 from `tests_require`
