### ISSUE TITLE
site.login() doesn't actually set site.logged_in

### ISSUE THREAD

**Issue by audiodude** [mwclient/mwclient#231]
The member variable `site.is_logged_in` is set here: https://github.com/mwclient/mwclient/blob/114b46c3370c202ce9abc2150406433c70cb7107/mwclient/client.py#L307

I have code that looks like this for retrying login when credentials expire (where login() is a method that calls `site.login(user, pass)`):

```
 try:
    page.save(wikicode, msg)
  except mwclient.errors.AssertUserFailedError as e:
    logger.warn('Got login exception, retrying login')
    login()
    page.save(wikicode, msg)
```

But it doesn't work. I think the reason is that the login() method doesn't actually set `site.logged_in` (it is set only in handle_api_response when 'anon' is not in userinfo).

So the question is, if the login method gets to the point where it calls `self.site_init()`, can we assume that we are logged in and set site.logged_in = True?

**Comment by danmichaelo** [comment]
Hm, the thing is,`site_init()` makes an API query call for 'userinfo' right away:

https://github.com/mwclient/mwclient/blob/114b46c3370c202ce9abc2150406433c70cb7107/mwclient/client.py#L145

Which leads to `handle_api_response()` being called. If you are really logged in, `self.logged_in` should therefore be set correctly at this point.

So this is odd.

A quick fix might be to re-initialize the site before logging in again (`site = ..`)

But to understand this, I think some more logging is needed. You could make an editable install (download mwclient, do `pip install -e` in the downloaded folder), then sprinkle in some `print()` statements, e.g. in the `raw_api` method, like so:

```python
def raw_api(self, action, http_method='POST', *args, **kwargs):
        """Send a call to the API."""

        // DEBUG REQUEST
        print('>>>', action, kwargs)

        try:
            retry_on_error = kwargs.pop('retry_on_error')
        except KeyError:
            retry_on_error = True
        kwargs['action'] = action
        kwargs['format'] = 'json'
        data = self._query_string(*args, **kwargs)
        res = self.raw_call('api', data, retry_on_error=retry_on_error,
                            http_method=http_method)

        // DEBUG RESPONSE
        print('<<<', res)

        try:
            return json.loads(res, object_pairs_hook=OrderedDict)
        except ValueError:
            if res.startswith('MediaWiki API is not enabled for this site.'):
                raise errors.APIDisabledError
            raise errors.InvalidResponse(res)
```

You might get some useful info from the last output before AssertUserFailedError is raised.

**Comment by AdamWill** [comment]
@audiodude last call before closing this - were you ever able to get the info Dan requested? thanks!

**Comment by travis00100** [comment]
Feel free to close. I worked around this issue another way but I don't remember how.

**Comment by audiodude** [comment]
Feel free to close, I worked around this issue another way but I don't remember how.
