### ISSUE TITLE
Site.blocks() only returns a single block

### ISSUE THREAD

**Issue by roysmith** [mwclient/mwclient#240]
https://en.wikipedia.org/wiki/Special:Log?type=block&user=&page=MariaJaydHicky&wpdate=&tagfilter=&subtype= shows that User:MariaJaydHicky has had multiple blocks.  But, the following code:

```
#!/usr/bin/env python                                                                                                                                     

from mwclient import Site
from pprint import pprint

site = Site('en.wikipedia.org')
blocks = site.blocks(users=['MariaJaydHicky'])

for b in blocks:
    pprint(b)
```
only returns a single block, and not even the most recent one:

```
./blocks.py
OrderedDict([('id', 3697119),
             ('user', 'MariaJaydHicky'),
             ('by', 'Courcelles'),
             ('timestamp',
              time.struct_time(tm_year=2011, tm_mon=11, tm_mday=9, tm_hour=22, tm_min=1, tm_sec=6, tm_wday=2, tm_yday=313, tm_isdst=-1)),
             ('expiry', 'infinity'),
             ('reason',
              'revoking talk page access because of attack on various '
              'individuals and groups'),
             ('nocreate', ''),
             ('autoblock', '')])
```

I'm running:
mwclient==0.10.0
Python 3.5.3

**Comment by roysmith** [comment]
Oh, I see what's going on.  What I wanted was:

`site.logevents(type='block', title='User:MariaJaydHicky')`

It's the difference between https://www.mediawiki.org/wiki/API:Blocks and https://www.mediawiki.org/wiki/API:Logevents

**Comment by marcfrederick** [comment]
Hey @roysmith, thanks for raising this issue and sorry for the late response. I've updated the documentation of `Site.blocks` to include a reference to `Site.logevents(type='block')` in #289.
