### ISSUE TITLE
Setup PyPI hook

### ISSUE THREAD

**Issue by waldyrious** [mwclient/mwclient#25]
According to my comment [here](https://github.com/mwclient/mwclient/pull/21#issuecomment-19550515), we should activate the pypi github hook. [Here are the instructions](http://docs.pythonpackages.com/en/latest/github-service.html). Can you do that, @danmichaelo? You now have access to mwclient's repo on both github and pypi.

**Comment by waldyrious** [comment]
Update: active development has moved to a new repo, [python-packages](https://github.com/python-packages/python-packages). The project URL remains http://pythonpackages.com, but it doesn't seem functional (I managed to login, but not much else).

**Comment by danmichaelo** [comment]
Ouch, http://pythonpackages.com is now redirecting to https://aclark.net 😮 

Anyways, I just added automatic PyPI releases from Travis (https://github.com/mwclient/mwclient/commit/7fb587134ee291ee9fc71e0cc02d25f93812b83e), so I think this is now covered?

**Comment by waldyrious** [comment]
Yes, that was precisely the intent :) We can close this now. 🎉
