### ISSUE TITLE
No such file or directory: 'mwclient'

### ISSUE THREAD

**Issue by Jennywooz** [mwclient/mwclient#250]
I put in the python app.

> $ import mwclient 

It gave me this error 

> import: command not found

Since import isn’t working I tried python3.

So I put...

> $  python3 mwclient

It gave me this error

> No such file or directory: 'mwclient'

**Comment by waldyrious** [comment]
Hi @Jennywooz, thanks for reporting your issue. Can I ask more details about what you're trying to accomplish with wmclient? That will help us figure out how to help you.

Also, have you seen the [mwclient documentation](https://mwclient.readthedocs.io/en/latest/)? Please take a look if you haven't, and let us know of any missing context or unclear instructions there, so we can improve it for you and others.

**Comment by ernstki** [comment]
@Jennywooz, it's been over a year and I'm sure you've figured it out by now, but mwclient is meant to be `import`ed as a library within a Python program, not invoked by commands entered at the command line.

Unpacking all the details of what I just said there is probably beyond the scope of this issue, but here's a crash course:

```bash
# see if it even got installed correctly
python -c 'import mwclient'

# make a small test program
echo "import sys
import mwclient

site = mwclient.Site('en.wikipedia.org')
catsearch = site.search('cat')
firstcat = next(catsearch)
print(firstcat['title'])" > firstcatpage.py

# run that program
python firstcatpage.py
```

If you have some programming experience already, then [this](https://docs.python.org/3/tutorial/interpreter.html) might be the place to start with learning about the Python interpreter. If not, [this](https://swcarpentry.github.io/python-novice-inflammation/) is a good start-from-square-one Python tutorial; be sure you don't skip the ["Setup" section](https://swcarpentry.github.io/python-novice-inflammation/setup.html).

Hope this helps.

**Comment by waldyrious** [comment]
Thanks @ernstki for the details and instructions. That was very kind of you. Even if this doesn't help @Jennywooz, it will certainly be useful to others who may be facing the same challenges.

On that note, since @Jennywooz never responded, I'll go ahead and close this issue. Happy to reopen later if needed.
