### ISSUE TITLE
Can't edit pages

### ISSUE THREAD

**Issue by scoopgracie** [mwclient/mwclient#251]
AttributeError: 'Page' object has no attribute 'edit'

**Comment by sim0nx** [comment]
With the latest published version you need to use
```
page.save()
```

**Comment by scoopgracie** [comment]
No, the Page object literally has no edit method.

**Comment by PierreSelim** [comment]
The edit method has been added in a recent commit f7c09a35fb6586375b6af52af6c9a0c6762691a1, which has not been released on PyPi.

So either you can update from the sources
Or you should use `page.save()`

**Comment by scoopgracie** [comment]
@PierreSelim Oh okay. Thank you!
