### ISSUE TITLE
Update version & publish to PyPI

### ISSUE THREAD

**Issue by RheingoldRiver** [mwclient/mwclient#252]
I keep having to re-update to development version to access Page.touch() when I upgrade other packages that use this as a dependency. I might be doing something wrong to make this happen, but could you update the version, which I think would also fix this? Thanks!

**Comment by danmichaelo** [comment]
Just published a new version now 🚀  https://github.com/mwclient/mwclient/releases/tag/v0.10.1

**Comment by RheingoldRiver** [comment]
Thanks!
