### ISSUE TITLE
Persist logins

### ISSUE THREAD

**Issue by dqwiki** [mwclient/mwclient#256]
When a bot needs to login frequently, there seems to be no way to persist that login beyond a single script run. It causes concerns for developers when there is a very high demand for the bot edits. I would like to be able to use the assert function of the login API ( https://www.mediawiki.org/wiki/API:Login#Additional_notes ) but that doesn't appear to be possible.

Talkpage notification: https://en.wikipedia.org/w/index.php?title=User_talk:AmandaNP&oldid=964855608#High_DeltaQuadBot_login_rate
Phabricator task: https://phabricator.wikimedia.org/T256533#6261565

**Comment by danmichaelo** [comment]
Persisting login sessions is outside the scope of mwclient, but you can pass mwclient a custom requests Session which includes a persistent cookiejar. Something like this:

```python
import os
import requests
from requests_oauthlib import OAuth1
from http.cookiejar import MozillaCookieJar
from mwclient import Site

cookiesFile = 'cookies.txt'

jar = MozillaCookieJar(cookiesFile)
if os.path.exists(cookiesFile):  # Only attempt to load if the cookie file exists.
    jar.load(ignore_discard=True, ignore_expires=True, expirydate=0)

connection = requests.Session()
connection.cookies = jar  # Tell Requests session to use the cookiejar.

site = Site('en.wikipedia.org', pool=connection)
if not self.logged_in:
    site.login(...)

# Then save the cookies to file
jar.save(ignore_discard=True, ignore_expires=True, expirydate=0)

# ... rest of script
```

Btw., mwclient will automatically send `assert=user` with each edit request, unless you pass `force_login=False` to `Site()`.

**Comment by dqwiki** [comment]
Thanks, i'll take a look at this.

**Comment by dqwiki** [comment]
@danmichaelo I implemented this and modified a few things so work. That says, there never seems to be any cookies being generated. Is that because I need to be using OAuth1 or should the old school login still generate them?

**Comment by danmichaelo** [comment]
Is the cookie file not created at all, or is it empty?


I just tested the code below with a bot password from https://www.mediawiki.org/wiki/Special:BotPasswords . First time I ran it, it created `cookies.txt` with 7 cookies. Second time, it read the cookies file and was automatically logged in.


```python
import os
import requests
from requests_oauthlib import OAuth1
from http.cookiejar import MozillaCookieJar
from mwclient import Site

BOT_USER = 'CHANGE-ME'
BOT_PASSWORD = 'CHANGE-ME'

cookies_file = 'cookies.txt'

cookie_jar = MozillaCookieJar(cookies_file)
if os.path.exists(cookies_file):
    # Load cookies from file, including session cookies (expirydate=0)
    cookie_jar.load(ignore_discard=True, ignore_expires=True)
print('We have %d cookies' % len(cookie_jar))

connection = requests.Session()
connection.cookies = cookie_jar  # Tell Requests session to use the cookiejar.

site = Site('en.wikipedia.org', pool=connection)
if site.logged_in:
    print('Already logged in as ' + site.username)
else:
    print('Logging in')
    site.login(BOT_USER, BOT_PASSWORD)

#
# Save cookies to file, including session cookies (expirydate=0)
cookie_jar.save(ignore_discard=True, ignore_expires=True)

# ... rest of script
```

**Comment by dqwiki** [comment]
I ran your script and it creates the cookie fine. When I go back to my old script, the system can see and read the cookie file. It's not being attached with the `mwclient.Site('en.wikipedia.org')` isn't taking it in.
`.logged_in` always returns false in my script.

**Comment by danmichaelo** [comment]
Did you include the `pool` argument on `mwclient.Site`? That's how you connect mwclient to the session that has the cookies. Something like this:

```
site = Site('en.wikipedia.org', pool=connection)
```

**Comment by dqwiki** [comment]
Perfect, that seems to have been the issue.

**Comment by danmichaelo** [comment]
Good to hear!
