### ISSUE TITLE
KeyError: 'reason' in mwclient.client.login()

### ISSUE THREAD

**Issue by rohieb** [mwclient/mwclient#258]
After an update from Python 3.5 to Python 3.7, I now sometimes (about 50% of the time) get strange tracebacks with our MediaWiki 1.31 instance, with both mwclient 0.10.0 (which the trace below is from) or mwclient 0.10.1:

```
Traceback (most recent call last):
  File "/opt/stratum0-calendar/bot.py", line 35, in update
    site.login(config.user, config.password)
  File "/opt/stratum0-calendar-venv/lib/python3.7/site-packages/mwclient/client.py", line 565, in login
    login['login']['reason'])
KeyError: 'reason'
```

Any ideas where it could come from? The bot runs on the same VM as MediaWiki itself, so it could also very well be related to the upgrade from PHP 7.0 to PHP 7.3…

**Comment by roysmith** [comment]
For what it's worth, I'm running Python 3.7.3 (and mwclient 0.10.0) and I'm not seeing this problem.

**Comment by danmichaelo** [comment]
@rohieb , you could try adding

    print(login)

right before the raise: https://github.com/mwclient/mwclient/blob/7c097f2a947122c2470f44a4f153dc44f57c09f4/mwclient/client.py#L564

so it becomes

```python
                else:
                    print(login)
                    raise errors.LoginError(self, login['login']['result'],
                                            login['login']['reason'])
```

That could give some more insight into what the actual response from the server is.

Alternatively, you could try reproducing it using a small script:

```python
from mwclient import SIte
site = Site('FIXME')
response = site.post('login', lgname='FIXME', lgpassword='FIXME', lgtoken=site.get_token('login'))
print(response)
```

Normally, you should get something like this for a failed login:

```python
OrderedDict([('login', OrderedDict([('result', 'Failed'), ('reason', 'Incorrect username or password entered. Please try again.')]))])
```

**Comment by rohieb** [comment]
Strange, the error vanished as mysteriously as it appeared without me changing anything, so I'm sadly no longer able to debug this. Maybe it was just a bad phase of the moon… Therefore I'm closing the issue until it happens again. Thanks for your comments nevertheless!
