### ISSUE TITLE
Patrol function

### ISSUE THREAD

**Issue by Fusion-thermo** [mwclient/mwclient#266]
Hello, currently some function are commented out in the code :
```
    # def block(self): TODO?
    # def unblock: TODO?
    # def patrol: TODO?
    # def import: TODO?
```
I am very interested in the patrol function, do you plan on adding it ?

By the way, thanks for the library, it's really useful.

**Comment by marcfrederick** [comment]
Hi @Fusion-thermo, sorry for taking so long to get back to you on this one. I've added the `Site.patrol` function in #293. It will be included in the next release, but it might still take some time before we're able to release it to PyPI. If you still need it and want to use it right now, you can install directly from Git (see [here](https://stackoverflow.com/a/20101940)).

```
$ pip install git+https://github.com/mwclient/mwclient.git@master
```

**Comment by Fusion-thermo** [comment]
Hi, thank you for the function, I will do that.
