### ISSUE TITLE
IMSLP Page : mwclient.errors.InvalidPageTitle: None

### ISSUE THREAD

**Issue by ramseyharrison** [mwclient/mwclient#270]
`site = mwclient.Site('imslp.org',path='/')
page=mwclient.page.Page(site,name="Symphony_No.7%2C_Op.92_(Beethoven%2C_Ludwig_van)") `
When creating this page, the following error is raised  : 
`raise mwclient.errors.InvalidPageTitle(info.get('invalidreason'))
`
I assume the issue has to do with the "%" in the name, given that no issue is raised with the following : 
`page=mwclient.page.Page(site,name="Piano_Concerto_No.1,_Op.15_(Beethoven,_Ludwig_van)") `

Is there a workaround for this? Why is it that the % sign appears to pose a problem?

**Comment by yaojin17** [comment]
Same problem. How did you solve that?

**Comment by AdamWill** [comment]
well, `%2C` is just the encoded form of a comma. If just passing an actual comma works, then...do that. Presumably it's getting encoded down the stack somewhere from mwclient, I would guess in requests.

So, the answer is "don't bother encoding characters in the page name yourself, just use the unencoded characters".
