### ISSUE TITLE
KeyError: 'expiry' missing in `page.info.protection`

### ISSUE THREAD

**Issue by yzqzss** [mwclient/mwclient#290]
If a protected page is without the 'expiry' key in its meta-info, mwclient will crash.

See also: https://github.com/mediawiki-client-tools/mediawiki-scraper/issues/131

---

info["protection"]: (normal protected page)
```
[OrderedDict([('type', 'edit'), ('level', 'sysop'), ('expiry', 'infinity')]), OrderedDict([('type', 'move'), ('level', 'sysop'), ('expiry', 'infinity')])]
```

info["protection"]: ([error page sample])
```
[OrderedDict([('type', 'edit'), ('level', 'sysop')]), OrderedDict([('type', 'move'), ('level', 'sysop')])]
```

>  Protected "System Recovery Status" ([Edit=Allow only administrators] (_indefinite_) [Move=Allow only administrators] (_indefinite_))

[error page sample]: https://www.linux-mips.org/wiki?title=System_Recovery_Status&oldid=66035

## How to reproduce:

```
session = requests.Session()
session.verify = False
requests.packages.urllib3.disable_warnings()
site = mwclient.Site("www.linux-mips.org", "/mediawiki/", "https", pool=session)
for page in site.allpages(namespace=0):
    pass
```

**Comment by marcfrederick** [comment]
There's definitely something weird going on here. There's another protected page on that wiki, for which the `expiry` is present.

```
$ curl -sk 'https://www.linux-mips.org/mediawiki/api.php?generator=allpages&gapnamespace=0&gapfilterredir=all&gapdir=ascending&gapfilterlanglinks=all&gaplimit=500&prop=info%7Cimageinfo&inprop=protection&iiprop=timestamp%7Cuser%7Ccomment%7Curl%7Csize%7Csha1%7Cmetadata%7Carchivename&continue=&meta=userinfo&uiprop=blockinfo%7Chasmsg&action=query&format=json' | jq -c '.query.pages[].protection | select(length > 0)'
[{"type":"edit","level":"sysop","expiry":"infinity"},{"type":"move","level":"sysop","expiry":"infinity"}]
[{"type":"edit","level":"sysop"},{"type":"move","level":"sysop"}]
```

In my opinion, we should still try to handle this case gracefully (e.g. by falling back to `None` as done in #291) instead of throwing an exception. The current behavior makes instantiating such pages straight up impossible, which is very unexpected from the perspective of an end-user (who typically has no influence on the configuration of the wiki).

**Comment by yzqzss** [comment]
This problem exists on other wikis as well.

See commit msg:

https://github.com/WikiTeam/wikiteam/commit/51ac495a59d13e896fb62d1d3400016f1fa47b62
