### ISSUE TITLE
httpauth only allows latin-1 characters in username and password

### ISSUE THREAD

**Issue by LaoshuBaby** [mwclient/mwclient#315]
Hello, today I am trying to use mwclient to edit Wikipedia. I want to test whether this framework is functional.

My code are show below:

```
user_agent = "laoshubaby's robot"
site = mwclient.Site(
    "zh.wikipedia.org",
    # path="/",
    clients_useragent=user_agent,
    httpauth=("快乐的老鼠宝宝", "my_password_in_plain_text")
)
# site.login("快乐的老鼠宝宝", "my_password_in_plain_text")


page = site.pages["User:快乐的老鼠宝宝/沙盒"]
text = page.text()
add_text = "是鼠宝宝的姬器人！"
page.edit(text + add_text, add_text)
```

If I try to login with `httpauth`` parameter, this will cause a error like:

```
PS C:\Programmer\learn_python> python wiki.py
Traceback (most recent call last):
  File "C:\Programmer\learn_python\wiki.py", line 37, in <module>
    site = mwclient.Site(
           ^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\mwclient\client.py", line 130, in __init__
    self.site_init()
  File "C:\Environment\Python\Python312\Lib\site-packages\mwclient\client.py", line 150, in site_init
    meta = self.get('query', meta='siteinfo|userinfo',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\mwclient\client.py", line 234, in get
    return self.api(action, 'GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\mwclient\client.py", line 285, in api
    info = self.raw_api(action, http_method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\mwclient\client.py", line 437, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\mwclient\client.py", line 399, in raw_call
    stream = self.connection.request(http_method, url, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Environment\Python\Python312\Lib\site-packages\requests\models.py", line 372, in prepare
    self.prepare_auth(auth, url)
  File "C:\Environment\Python\Python312\Lib\site-packages\requests\models.py", line 603, in prepare_auth
    r = auth(self)
        ^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\requests\auth.py", line 95, in __call__
    r.headers["Authorization"] = _basic_auth_str(self.username, self.password)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python312\Lib\site-packages\requests\auth.py", line 57, in _basic_auth_str
    username = username.encode("latin1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-6: ordinal not in range(256)
```

**Comment by LaoshuBaby** [comment]
By the way, you may found the commented `site.login()` in my code, that's because this only work for standard wikipedia, it will request a link like this:

```
https://zh.wikipedia.org/w/api.php?meta=siteinfo|userinfo|userinfo&siprop=general|namespaces&uiprop=groups|rights|blockinfo|hasmsg&continue=&action=query&format=json
```

On wikipedia this login method indeed work and successfully create a [edit](https://zh.wikipedia.org/w/index.php?title=User:%E5%BF%AB%E4%B9%90%E7%9A%84%E8%80%81%E9%BC%A0%E5%AE%9D%E5%AE%9D/%E6%B2%99%E7%9B%92&diff=next&oldid=80329521), but some other self hosted wiki's api endpoint maybe like "https://example.domain/api.php"

**Comment by AdamWill** [comment]
This is kinda really [a requests issue](https://github.com/psf/requests/issues/4564), but we can work around it fairly easily at the mediawiki level, so let's do that.

It seems a bit concerning that that issue indicates requests was already in security-maintenance-only mode in 2020. Maybe we need to look at switching to httpx at some point. Sigh.

**Comment by AdamWill** [comment]
Can you try with https://github.com/mwclient/mwclient/pull/316 ? That should work. Thanks!

**Comment by LaoshuBaby** [comment]
> That should work.

my code:
```python
import mwclient
site = mwclient.Site(
    "zh.wikipedia.org",
    clients_useragent="laoshubaby's robot",
    httpauth=("快乐的老鼠宝宝", "my_password_in_plain_text"),
)
page = site.pages["User:快乐的老鼠宝宝"]
text = page.text()
page.edit(text+"SUCCESS", "mwclient#316")
```

I use changed `client.py` replace installed one, now it truly not crashed by non ascii character, but I got an error like this now

```
PS C:\Programmer\learn_python> py wiki.py
Traceback (most recent call last):
  File "C:\Programmer\learn_python\wiki.py", line 37, in <module>
    page.edit(text+"SUCCESS", "mwclient#316")
  File "C:\Environment\Python\Python311\Lib\site-packages\mwclient\page.py", line 184, in edit
    return self._edit(summary, minor, bot, section, text=text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\mwclient\page.py", line 200, in _edit
    raise mwclient.errors.AssertUserFailedError()
mwclient.errors.AssertUserFailedError: By default, mwclient protects you from accidentally editing without being logged in. If you actually want to edit without logging in, you can set force_login on the Site object to False.
```

**Comment by AdamWill** [comment]
Oh, wait, I think I see the confusion here.

When you set `httpauth`, that's not for logging in to mediawiki. It's for [HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) - it's for editing a wiki which is, for some reason, protected by an HTTP authentication layer. Public wikipedia, of course, is not.

If what you want to do is log in to wikipedia, don't use `httpauth`. Instead, after initializing `site`, call `site.clientlogin(username="快乐的老鼠宝宝", password="your_password_in_plain_text")`. Like this:

    import mwclient
    site = mwclient.Site(
        "zh.wikipedia.org",
        clients_useragent="laoshubaby's robot",
    )
    site.clientlogin(username="快乐的老鼠宝宝", password="my_password_in_plain_text"),
    page = site.pages["User:快乐的老鼠宝宝"]
    text = page.text()
    page.edit(text+"SUCCESS", "mwclient#316")

can you try that? thanks!

**Comment by LaoshuBaby** [comment]
> edit: if this is a bot account using bot passwords, instead use `site.login(username="快乐的老鼠宝宝", password="my_password_in_plain_text")`.

In fact, I initially tried using this method and it worked successfully.

![图片](https://github.com/mwclient/mwclient/assets/42690037/b6efac09-5653-4944-aaad-960bc1e15f11)

Because the document considers it "old-school," I doubt if it is not recommended.

Moreover, it is grouped with OAuth (which is generally considered more secure but also more complicated in operation), so I mistakenly thought that OAuth, httpauth, and `site.login()` are three equivalent methods with the same final effect.

Thank you for providing the example. It works. For my subsequent bulk editing, I obviously need an additional dedicated bot account (following community procedures), so I think `site.login()` would be a better choice.

Anyway, after using your modified code, I did not encounter latin-1 encoding errors, so the original problem is indeed solved.

**Comment by AdamWill** [comment]
I see, thanks for the explanation. I'll see if I can think of a way to make it clearer in the docs that httpauth is not just an alternative to oauth and `login()`. We also probably need to explain `clientlogin()` there.
