### ISSUE TITLE
Update authentication documentation page

### ISSUE THREAD

**Issue by AdamWill** [mwclient/mwclient#322]
The info on authenticating in the docs doesn't cover `clientlogin()`, and - as suggested in https://github.com/mwclient/mwclient/issues/315 - could make it clearer that the options that allow HTTP authentication aren't alternatives for logging into mediawiki itself.

**Comment by marcfrederick** [comment]
I've created a PR (#324) trying to clarify this a bit.

---

Honestly, in my opinion, the current implementation is unnecessarily complex and confusing. We have the httpauth parameter, which supports both a requests.auth.AuthBase object and a tuple[str, str]/list[str]. Additionally, we have OAuth[^1] parameters1, which are used to initialize a requests_oauthlib.OAuth1 object.

Dropping the OAuth1 parameters would simplify the constructor and eliminate unexpected behavior when a user passes those parameters in addition to httpauth[^2]. This change would also allow us to remove the dependency on requests_oauthlib and depend directly on requests.

```python
import mwclient
import requests_oauthlib

# Current
client = mwclient.Site(
    'en.wikipedia.org',
    consumer_token='foo',
    consumer_secret='bar',
    access_token='baz',
    access_secret='qux'
)

# Suggested
auth = requests_oauthlib.OAuth1('foo', 'bar', 'baz', 'qux')
client = mwclient.Site('en.wikipedia.org', httpauth=auth)
```

This would still leave some potential confusion around the difference between `Site.login()` and passing `httpauth` to the constructor, but might remove at least some complexity from the whole thing.

[^1]: `consumer_token`, `consumer_secret`, `access_token`, and `access_secret`
[^2]: `httpauth` is silently ignored when `consumer_token` is not `None`.

**Comment by AdamWill** [comment]
https://github.com/mwclient/mwclient/pull/332 is a follow-up to document `clientlogin`.

**Comment by AdamWill** [comment]
@marcfrederick I'm not sure your idea for oauth works, btw. Passing an `httpauth` arg sets up *HTTP* authentication. It's not *mediawiki API* authentication. It's for use when the deployment has HTTP-level authentication you have to pass to even reach the API at all. The oauth token stuff is for authentication *to the mediawiki API* using oauth. AIUI, anyway.
