### ISSUE TITLE
/w/api.php - not where my default install api.php is

### ISSUE THREAD

**Issue by raindog308** [mwclient/mwclient#34]
As of mediawiki-1.22.3 (and probably earlier), a default mediawiki install doesn't have a /w/api.php path.  api.php is instead installed in default.

**Comment by danmichaelo** [comment]
This is now in the documentation: http://mwclient.readthedocs.io/en/latest/user/connecting.html#the-api-endpoint-location

I'm not really sure what more can be done, so I'm closing this for now.
