### ISSUE TITLE
FYI: mwclient broken on 1.43.0-wmf.17, writeapi flag removed

### ISSUE THREAD

**Issue by lucaswerkmeister** [mwclient/mwclient#344]
You’ll probably be interested in [T371977](https://phabricator.wikimedia.org/T371977).

Regardless of what happens in that task on the Wikimedia / MediaWiki side, you might want to remove the relevant `writeapi` code in the library. In particular, checking for `writeapi` in the `meta=siteinfo` output is basically pointless these days – that flag has been [hard-coded to `true`](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/392542/10/includes/api/ApiQuerySiteinfo.php) (before it was removed entirely, see T371977) since April 2018, i.e. the code raising `NoWriteApi` has been effectively dead code for over six years.

**Comment by AdamWill** [comment]
well, the code was removed six years ago *in upstream RCS* is not the same as "it's been dead code for over six years", because people run old software. I don't know what the oldest mediawiki deployment out there is, but probably pretty old.

still...removal six years ago is probably old *enough* that we can just get rid of this rather than try to handle both ways.

thanks for flagging it up!

**Comment by lucaswerkmeister** [comment]
> well, the code was removed six years ago _in upstream RCS_ is not the same as "it's been dead code for over six years", because people run old software. I don't know what the oldest mediawiki deployment out there is, but probably pretty old.

Fair enough :) (If you want a horror story, [IMSLP Special:Version](https://imslp.org/wiki/Special:Version) reports 1.18!)

> still...removal six years ago is probably old _enough_ that we can just get rid of this rather than try to handle both ways.

I’d also say that the risk of the change in #345 for old wikis is pretty small – behavior will only change for wikis that actually tried to disable `writapi` (I don’t know if that was ever common), and even then, mwclient would hopefully just fail differently (and _after_ making an API request rather than before).

**Comment by AdamWill** [comment]
PR is merged now. I'll really try and get to working on the release soon.
