### ISSUE TITLE
where did writeapi go?

### ISSUE THREAD

**Issue by WolfgangFahl** [mwclient/mwclient#355]
Thanks for creating a new version of mwclient. Unfortunately some of my code seems to break now e.g.

```python
def needs_login(self) -> bool:
        """
        Check if login is required for the wiki.

        Returns:
            True if login is required, False otherwise.
        """
        site = self.get_site()
        login_needed: bool = not site.writeapi
        return login_needed
```

**Comment by WolfgangFahl** [comment]
I asked ChatGPT about this and it looks like the writeapi attribute habe been known well enough to have been picked up in it's training data:

**prompt**
does the mwclient library have a writeapi attribute?

**ChatGPT**

Yes, the mwclient library has a writeapi attribute.

In mwclient, the writeapi attribute is a boolean that indicates whether the MediaWiki instance you are connected to has the write API enabled. This attribute is useful for checking if you can perform write operations (like editing pages) using the API.

Here’s an example of how you can check for the writeapi attribute in a mwclient site object:


```
python
import mwclient

# Connect to a MediaWiki site
site = mwclient.Site('example.org')

# Check if the write API is enabled
if site.writeapi:
    print("Write API is enabled")
else:
    print("Write API is not enabled")
```
This attribute is automatically determined based on the API info provided by the MediaWiki instance, so you don't need to set it manually.

**Comment by AdamWill** [comment]
It has been [hardcoded to True and deprecated upstream since mediawiki 1.32](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/392542/10/includes/api/ApiQuerySiteinfo.php), and upstream briefly removed it, which broke all mwclient code: https://phabricator.wikimedia.org/T371977 . So we took out use of it intentionally in the new release.

We *could* put it back in as a hardcoded True, I guess, but...eh. It should be fairly straightforward to change your code. That function will always return `False` with any mediawiki version later than 1.32, so it's kinda pointless.

**Comment by AdamWill** [comment]
Also this reminds me I never got around to writing the release notes for 0.11.0 yet, which, whoops. I should get on that. Sorry.

**Comment by WolfgangFahl** [comment]
@AdamWill  - thx for commenting - i implemented the following workaround which seems to work as intended for now. Please note that my https://github.com/WolfgangFahl/pymediawikidocker will only actively create
1.35.13,1.38.6 and 1.39.8, 1.40.4, 1.41.2 and 1.42.1 

but potentially can still be used to create e.g. 1.27 versions and there are still sites having that version or even lower.

```python
        login_needed: bool = False
        site = self.get_site()
#       login_needed: bool = not site.writeapi
        if not site.initialized:
            try:
                self.site.site_init()
                if hasattr("site", "writeapi"):
                    login_needed = not site.writeapi
                else:
                    login_needed = not "writeapi" in site.site
            except Exception as ex:
                if hasattr(ex, "args") and "readapidenied" in ex.args:
                    login_needed=True
                pass


        return login_needed
        
```

**Comment by AdamWill** [comment]
I'm still not sure that function is really correct, though. It's possible for permissions to be more atomic than just "you can write to the entire wiki anonymously or not". For instance, on the Fedora wiki, you can write to one namespace anonymously, but not the rest of the wiki.

Are you aware of the `Page.can()` method? That should give accurate results, I believe.

**Comment by WolfgangFahl** [comment]
@AdamWill  fortunately all the wikis for my usecases are under my control so the special and exotic cases that might be possible are currently not relevant for me. Thanks for pointing out these possible cases.

**Comment by marcfrederick** [comment]
Closing this as the change was intentional (#345) and there doesn't seem to be an immediate issue anymore.
