### ISSUE TITLE
Host auto-generated documentation at ReadTheDocs.org

### ISSUE THREAD

**Issue by waldyrious** [mwclient/mwclient#40]
Using Sphinx's [autodoc extension](http://sphinx-doc.org/ext/autodoc.html#module-sphinx.ext.autodoc) to pull data from from the docstrings.

From reading that page, it seemed to require quite a lot of custom documentation markup to get autodoc to work. [Apparently I wasn't the only one thinking the same](http://stackoverflow.com/questions/2701998/sphinx-autodoc-is-not-automatic-enough). Fortunately, the solution mentioned on that page has since been integrated as the [sphinx-apidoc](http://sphinx-doc.org/man/sphinx-apidoc.html) tool, which is meant to be used with autodoc.

[This tutorial](http://codeandchaos.wordpress.com/2012/07/30/sphinx-autodoc-tutorial-for-dummies/) seems to imply that no special documentation format is required when adding docstrings to be extracted with apidoc+autodoc. But surely there must be some way to, say, describe parameters, and I assume rST formatting is parsed as well.

As soon as we know how to format the docstrings we can start adding the information from the wiki to the actual code, and setup the github hook.

@danmichaelo [said](https://github.com/mwclient/mwclient/issues/12#issuecomment-19694375) back in issue #12:
> My impression is that there are few standards when it comes to Python documentation... I tried to look at some other projects now. The MongoDB driver for instance seems to have a good style:

> https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/mongo_client.py

> It uses `:Parameters:` and then lists the parameters as a normal list, and the result is this:

> http://api.mongodb.org/python/current/api/pymongo/mongo_client.html#module-pymongo.mongo_client

to which I [responded](https://github.com/mwclient/mwclient/issues/12#issuecomment-20447515):

> I did look into the mongodb example but I'm a little unsure about the keywords and formatting. For example, the list [here](https://github.com/danmichaelo/mwclient/blob/sphinx/mwclient/client.py#L489), while formatted similarly to the mongodb example [here](https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/mongo_client.py#L117), doesn't seem to be interpreted the same way by Sphynx. I'm not sure whether that has to do with using the "parameters" keyword before it, or something else.

@danmichaelo can you shed some light on this? It'd be nice to move forward now that all documentation has been moved to the wiki.

**Comment by waldyrious** [comment]
@danmichaelo did you get the chance to try any more of this? If not, any plans to do so soon?

On a related note: I just found out about [Syntaf/travis-sphinx](https://github.com/Syntaf/travis-sphinx) ("A standalone script for automated building and deploying of sphinx docs via travis-ci"). It sounds pretty interesting. Is that something we could use rather than ReadTheDocs? And even if we could, should we?

**Comment by danmichaelo** [comment]
I'm giving ReadTheDocs a try now..

**Comment by waldyrious** [comment]
Awesome :) That seems to be quite a bit of extra stuff, though. I wonder if the travis-sphynx setup could be any lighter (i.e. more of the infrastructure off-loaded to travis-sphinx or travis itself). If so, it could be an interesting alternative, although I wonder if building the docs in local clones would remain possible...

As I mentioned [earlier](https://github.com/mwclient/mwclient/issues/12#issuecomment-19547508), a minimal setup would be quite nicer. And although I [ruled pycco out](https://github.com/mwclient/mwclient/issues/12#issuecomment-19551217) at the time due to git hooks (which, IIRC, would rebuild documentation on commits) not being able to be integrated into the repo, I wonder if a travis-based process could replace that. Again, the concerns about locally building the docs could still apply.

Regardless, don't let my possibly incoherent ramblings distract you. I just wanted to put these thoughts in writing :)

**Comment by danmichaelo** [comment]
Sure, it's a valid concern :) Actually, I think ReadTheDocs only uses the `conf.py` file, not the make-files, but including them in the Git repo makes it easier to build the documentation locally for testing. I guess the same would be the case if we used travis-sphinx.

Apart from the conf and make files, the remaining files are just actual (manually created) documentation. I've split it into a short "user guide" followed by a "reference guide" where the `autodoc` extracted docstrings goes.

Right now, the main issue I have is to get the headings level right. In the current state, the html version looks fine (which is most important), but the first level headings are duplicated in the latexpdf version. If I remove, say, the "User guide" heading from docs/source/user/index.rst , headings become correct in the latexpdf version, but the top level headings "User guide" disappears from the left TOC in the html version.

**Comment by danmichaelo** [comment]
It's semi-public (not indexed) at http://mwclient.readthedocs.org/ now

**Comment by waldyrious** [comment]
Looks amazing already! Let me know when I can start submitting improvements / converting the wiki docs to in-code documentation :D

**Comment by PierreSelim** [comment]
Read The Docs is a good options, thanks @waldyrious and @danmichaelo it looks great. :)

**Comment by danmichaelo** [comment]
@waldyrious Anytime :+1: I was also thinking about converting the wiki docs, so that would be great. Also, let me know if you decide to create an account at readthedocs, and I'll add you to the project. Not that there's so much to configure there, but it's always nice to have more than one person with access in case I suddenly die or something :D

**Comment by waldyrious** [comment]
Hahah, yeah, bus factor tends to happen quite a bit here on github (general availability limits, etc.). I've created an account there as "waldyrious".

As for the conversion of the wiki docs, let me know if I got this right: so every function with triple-quoted docstrings in the [Site class](https://github.com/mwclient/mwclient/blob/master/mwclient/client.py#L35) will automatically show up at http://mwclient.readthedocs.org/en/master/reference/site.html? If they don't have docstrings, then they just don't show up?

And what reference should I use for the formatting, arguments, anchors to other classes/functions, etc.? [Above](https://github.com/mwclient/mwclient/issues/40#issuecomment-57104907) you mentioned some styles, and suggested the Google one as the most readable, Is that still the case? Should I use that as the guideline, or do you have to configure something before it works?

Also, a question more out of curiosity: are the docs built automatically with every commit, or regularly after a set time limit, or what?

Btw: should we close this issue now? :D

Finally, a nitpick: I wonder if it would be worth splitting the `Site` class to its own file (or renaming the `client.py` file, since it seems to be mostly the `Site` class anyway)

**Comment by danmichaelo** [comment]
> Hahah, yeah, bus factor tends to happen quite a bit here on github (general availability limits, etc.). I've created an account there as "waldyrious".

Great

>As for the conversion of the wiki docs, let me know if I got this right: so every function with triple-quoted docstrings in the [Site class](https://github.com/mwclient/mwclient/blob/master/mwclient/client.py#L35) will automatically show up at http://mwclient.readthedocs.org/en/master/reference/site.html? If they don't have docstrings, then they just don't show up?

Correct! And this is caused by the [autoclass](http://sphinx-doc.org/ext/autodoc.html#directive-autoclass) directive in https://github.com/mwclient/mwclient/tree/master/docs/source/reference/site.rst . So if we want to document more classes, we need to create files for those as well (and add them to the list in reference/index.rst).

>And what reference should I use for the formatting, arguments, anchors to other classes/functions, etc.? [Above](https://github.com/mwclient/mwclient/issues/40#issuecomment-57104907) you mentioned some styles, and suggested the Google one as the most readable, Is that still the case? Should I use that as the guideline, or do you have to configure something before it works?

I still try to use the "Google style", yes. It is supported by the napoleon plugin which is included by default in newer versions of Sphinx. So you should be able to test build docs locally by

    pip install Sphinx
    cd docs
    make html

I guess we should add that information to https://github.com/mwclient/mwclient/blob/master/docs/source/development/index.rst as well

> Also, a question more out of curiosity: are the docs built automatically with every commit, or regularly after a set time limit, or what?

With every commit, I enabled the git hook before my last commit and it seems to work. You can inspect build progress on https://readthedocs.org/projects/mwclient/builds/ (the reason for three builds was that it checked three branches, I've unchecked two of those now so it only builds master / latest).

> Btw: should we close this issue now? :D

:+1: 

> Finally, a nitpick: I wonder if it would be worth splitting the `Site` class to its own file (or renaming the `client.py` file, since it seems to be mostly the `Site` class anyway)

Agree, I've just postponed it since it can break things.. Hopefully most people use `from mwclient import Site`, not `from mwclient.client import Site`, but you never know :) It keeps bothering me though, so we should probably just get it done.

**Comment by danmichaelo** [comment]
> If they don't have docstrings, then they just don't show up?

Seems like there's actually a flag `:undoc-members:` to include those as well, but I'm not sure if there is a need to include every "internal" method.

**Comment by waldyrious** [comment]
Good to know about the flag. For now let's keep it off, but maybe later it might occur us to activate it to encourage full documentation and invite participation (e.g. like the red links in Wikipedia).

I will also open an issue to track the Site class thing, please fix the title as appropriate.

**Comment by waldyrious** [comment]
Quick question: is there a convention to mark optional vs. required arguments, or is that supposed to be evident from the function signature (i.e. which arguments have default values)?

Also, looking at the contents of our wiki pages, would you say the whole contents of the pages ought to be moved to code comments, e.g. examples, etc.? Or should we restrict code comments to reference-like documentation, and leave tutorials for the wiki (linking them from the docs)? Or should we forgo the wiki and use checked-in files like README.md and REFERENCE.md, so that local clones will have access to them (without having to separately clone the wiki repository)? Or are those kind of documents meant to be in the "User guide" (particularly REFERENCE.md) and "Development" (particularly README's Contributing section) branches of the html docs?

So many questions... I think we need an overall documentation strategy and guidelines so we can work on it collaboratively and know what to put where.

**Comment by danmichaelo** [comment]
> Quick question: is there a convention to mark optional vs. required arguments, or is that supposed to be evident from the function signature (i.e. which arguments have default values)? I'm asking because on the wiki that is specified explicitly.

Not sure

> Also, looking at the contents of our wiki pages, would you say the whole contents of the pages ought to be moved to code comments, e.g. examples, etc.? Or should we restrict code comments to reference-like documentation, and leave tutorials for the wiki (linking them from the docs)? Or should we forgo the wiki and use checked-in files like README.md and REFERENCE.md, so that local clones will have access to them (without having to separately clone the wiki repository)? Or are those kind of documents meant to be in the "User guide" (particularly REFERENCE.md) and "Development" (particularly README's Contributing section) branches of the html docs?

Seems to me like quite a lot of the wiki tutorials can go into the "User guide", while shorter examples and method references can go into code comments (ending up in the "Reference guide").

I'm not really sure about the role of REFERENCE.md , perhaps it can be moved into the "User guide" as "Implementation details" or something like that? Yet, at least some of the content seems like it can be incorporated into code comments..

> So many questions... I think we need an overall documentation strategy and guidelines so we can work on it collaboratively and know what to put where.

Yeah, might be hard to formulate though.
