### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fhocutt** [mwclient/mwclient#52]
Python 3 compatibility would make mwclient more useful for new Python developers and new Python projects.

**Comment by eighthave** [comment]
any word on this?  This is the last library that is preventing us from moving F-Droid tools to python3.

**Comment by danmichaelo** [comment]
Funny, I actually fixed this last weekend. Since the test suite is quite incomplete I wanted to do some testing before pushing though. I'll push it tomorrow and ping you so you can test it.

**Comment by danmichaelo** [comment]
Sorry for the delay, got absorbed in another project :) The dev. version should now be Python 3 compatible. You can install it using:

    pip install -U git+git://github.com/mwclient/mwclient.git

Please leave a comment if you run into any problems!

**Comment by eighthave** [comment]
Thanks!  I'll check it out once I'm back working on the fdroidserver project again.

**Comment by mvdan** [comment]
@danmichaelo any news? We can't do releases of fdroidserver in python3 unless there's a mwclient release with python3 support too.

If master should work fine under python3 and you'd like us to test it and report back, we can do that too.

**Comment by danmichaelo** [comment]
@mvdan I'll schedule a release this weekend. It's definitely about time :)

**Comment by danmichaelo** [comment]
Done
