### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by fhocutt** [mwclient/mwclient#53]
Add unit tests for the most commonly used and frequently updated portions of the library. This will make debugging easier and will allow the use of automated testing if desired.

**Comment by PierreSelim** [comment]
I have started writing few tests for some error raised that are not tested in https://github.com/PierreSelim/mwclient/commits/increase_coverage It's far from perfect but it allows to spot regression / change on that part.

**Comment by danmichaelo** [comment]
Awesome! I added a few comments.

**Comment by marcfrederick** [comment]
Closing this in favor of #350. As of right now we're around 75% coverage 🚀.
