### ISSUE TITLE
Make https default

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#70]
Sending credentials without encryption is bad, so https should be the default, but this is a breaking change – there are probably MediaWiki installations on sites that don't support SSL, so I'm filing it for 0.8.0.

**Comment by hartman** [comment]
There are notes about HTTP insecure post traffic by this library.
https://phabricator.wikimedia.org/T105794

**Comment by PierreSelim** [comment]
Thank you @hartman for the notification, I think this is a good question, what should an API client do when redirected to HTTPS (fail, silently fallback to HTTPS, etc.) ?

**Comment by danmichaelo** [comment]
:+1: for the notification. And yeah, it's a good question. At least there should be some logging.warning, but then many users might fail to notice that. To avoid the question, I try to rather get a version defaulting to https out quickly :)
