### ISSUE TITLE
Configure default logger

### ISSUE THREAD

**Issue by Gui13** [mwclient/mwclient#82]
https://docs.python.org/3.1/library/logging.html#configuring-logging-for-a-library

Otherwise, when using mwclient you get this message :

    No handlers could be found for logger "mwclient.client"

**Comment by scholer** [comment]
Uhm... What exactly do you mean by configuring a default logger? Usually it is up to the consuming app to configure/initialize the logging system. Libraries should not try to configure the logging system, that would just cause issue for the library's clients.
Or do you mean that mwclient doesn't make enough use of the logging library? Currently it is only the client.py module that produces logging messages. However, it seems to follow the convention of using a module-level logger called logging.getLogger(__name__).

**Comment by Gui13** [comment]
Well, it is simply good manners: I wasn't using the logging facility in my code, and I struggled to understand where the warning came from.

As said in the doc, adding an empty handler will prevent the logging module to complain about a missing log handler, and will clear out this error message, so that a user that actually wants to use logging can still do, and those who do not don't need to add this code:

    class NullHandler(logging.Handler):
    def emit(self, record):
        pass
    logging.getLogger("mwclient.client").addHandler(NullHandler())


Otherwise, you force anyone to actually use Logging and set up the "mwclient.client" handler if they want to get rid of this message..

**Comment by danmichaelo** [comment]
Thanks @Gui13 , seems like the NullHandler is an accepted way of solving this, I wasn't aware of that.

**Comment by scholer** [comment]
Yes, thanks @Gui13 for explaining.

**Comment by Gui13** [comment]
Thanks!

**Comment by scholer** [comment]
Just a minor after thought / note: Having a null handler attached also means that logging messages of severity WARNING or higher will no longer be printed to stderr (which is the default behaviour when no handlers are attached). This could mean that users who expect to see warnings on stderr when something is wrong will wonder why this didn't happen. Still, the having a null-handler is probably the better option, as long as library users know that they *must* set up logging to have warnings and errors displayed.

**Comment by danmichaelo** [comment]
Hm, that's not my experience. With no logger configured, I only get 'No handlers could be found for logger "mwclient.client"' no matter what level.

But in any case, we need to assume that logging messages are not seen by the user. For anything critical, we should raise an exception instead.
