### ISSUE TITLE
Retry on connection error?

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#85]
Currently, mwclient will sleep a little and retry if it receives a `requests.exceptions.ConnectionError`, caused by issues such as DNS failure, refused connection

https://github.com/mwclient/mwclient/blob/master/mwclient/client.py#L270-L274

While this can be practical when working on unstable network connections, it's definitely no good that the library also keeps retrying if you happen to make a typo in the hostname when initializing the `Site`...

One solution could be to raise the error directly if we get it from the *first* request to a site, and keep retrying otherwise.

But perhaps this is just messy, and we should leave the responsibility of handling ConnectionError on the application using the library?

**Comment by scholer** [comment]
Both are valid arguments for and against retrying the connection. I guess a developer could set <max_retries> to get the desired behaviour. But obviously it would be good to have good/sane default behaviour. For my purposes, the current solution works just fine -- hostname typos would only happen during initial configuration. In this case, retrying the connection doesn't hurt. Although retrying 25 times might be a bit excessive. I guess having a property indicating whether the the Site connection has initially succeeded might be a good solution.

**Comment by danmichaelo** [comment]
Yeah, I agree that it's quite convenient. I just checked my bot logs, and short connection problems were quite frequent. Then I guess I will just fix it so it doesn't retry during `site_init()`.

**Comment by danmichaelo** [comment]
#79 is *somewhat* related ("unexpected behaviour when making a hostname typo"). We could probably raise the same error in both cases.
