### ISSUE TITLE
Propose logo

### ISSUE THREAD

**Issue by c-martinez** [mwclient/mwclient#88]
I would like to suggest this logo for mwclient:

![mwclient_logo](https://cloud.githubusercontent.com/assets/7782231/8400154/389f85a6-1e1a-11e5-97dd-37565facaaf9.png)

**Comment by waldyrious** [comment]
Kudos for the initiative, but I think this logo is too complex. Maybe a mix of the [single puzzle piece icon](https://commons.wikimedia.org/wiki/File:Wikipedia_affiliative_mark.png) with the python logo? The shapes are kinda similar, a little tweaking could potentially make a nicely fusion of both concepts. Perhaps the easiest way is starting out with the python logo, which is simpler, and tweak its shape to resemble a puzzle icon. What do you think?

**Comment by danmichaelo** [comment]
Since mwclient works with all mediawiki installations, I would prefer not limiting the logo to Wikipedia. I'm not sure, but I also guess trademark protection could also prevent us from using the logos like this?

What do you think about basing the logo on the mediawiki :sunflower:  instead? Perhaps in a [simplified version](https://www.mediawiki.org/wiki/File:Concept-Hackathon-Logo-AMS.png)? Perhaps using the Python colors (yellow sunflower, blue brackets)?

**Comment by waldyrious** [comment]
That's a good point. However just the python colors in the (simplified) MW logo doesn't seem like it'd be enough, IMO, especially since the MW logo is [already](https://commons.wikimedia.org/wiki/Category:MediaWiki_logos) a yellow sunflower with blue brackets. Perhaps using the python shape as the flower, all in yellow, with the mediawiki brackets around it?

**Comment by danmichaelo** [comment]
That seems like a path worth pursuing. I don't think the Python logo can be used as-is because of trademark, but perhaps some simplified version. Or perhaps a snake instead, if someone can make it :)

**Comment by waldyrious** [comment]
Relevant passages from the [PSF trademark policy](https://www.python.org/psf/trademarks/) (emphasis mine):

> stating accurately that software is written in the Python programming language (...) is always allowed. In those cases, you may use the word "Python" or the **unaltered** logos to indicate this, without our prior approval. This is true both for non-commercial and commercial uses.

and

> Any use of a derived (modified) logo for any **commercial purpose** must also be approved first by the PSF. We will generally be unable to do this, because of the confusion it may cause.

And then near the end there's this section which specifically addresses our case:

> _**Derived Logos**_

> Derived logos must always be sufficiently different from the Python logos to allow the community to tell the difference. For example, if you want to create a derived logo for a local Python user group, you might be able to insert an unaltered Python logo graphic into the local group's name in a way that does not cause confusion. But confusingly similar derived logos are not allowed. This includes entwining Python logos with other logos, or connecting them together in a confusing manner. **Logos that simply change the colors** or fonts require permission from the PSF Trademarks Committee.

> (...)

> **We recommend contacting the PSF for permission for all derived logos** to avoid placing a confusing logo into wide-spread use. Contacting us is not a requirement (...) when using freely distributable derived logos that have already been approved by the PSF. (...)

Given the above, I believe it could be easier to simply use a snake icon, such as [one of these](https://commons.wikimedia.org/wiki/Category:Snake_icons) or something inspired by [these](https://commons.wikimedia.org/wiki/Category:Python_icons). I particularly like the PyJS one:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Pyjs-logo.png/120px-Pyjs-logo.png)

I guess we could make something similar but using square brackets instead.

**Comment by danmichaelo** [comment]
Thanks for checking that!

So... "a vegetarian snake eating a sunflower" :D No, but seriously, I like the PyJS logo, and the idea of using a snake in general.

**Comment by waldyrious** [comment]
Here's a quick sketch, to bring more ideas to the table ;)

![Imgur](http://i.imgur.com/jsHTPVSm.jpg)

**Comment by waldyrious** [comment]
We could also take some inspiration from [these](https://commons.wikimedia.org/wiki/Category:Decorative_knots), since they can look both like flowers and like snakes.

**Comment by c-martinez** [comment]
Nice ideas! I'll see if I can persuade someone with drawing skills to help out.

**Comment by c-martinez** [comment]
Ok, not very professional but this is best I could do with my limited skills:

![mwlogo_v1](https://cloud.githubusercontent.com/assets/7782231/8424320/0900de0a-1ef9-11e5-8373-87f4f6486830.png)

Any thoughts?

**Comment by PierreSelim** [comment]
It looks nice to me!

**Comment by waldyrious** [comment]
Very nice! Can we have an svg version of it? That way I could try a few tweaks, but overall I love the idea, it looks great.

Not sure how close to the official Python logo that may be considered -- it might be better to contact the PSF regardless just to be safe.

**Comment by c-martinez** [comment]
Except github will not let me post SVG figures here, suggestions?

**Comment by danmichaelo** [comment]
Hm, guess they consider it a security risk… Can you use some other file sharing service, and link to it? Like https://hostr.co ?

**Comment by waldyrious** [comment]
I'd suggest posting the svg source code as a gist instead.

**Comment by c-martinez** [comment]
Good idea. Let's see if this works:

https://gist.github.com/c-martinez/5651e08911e576f50d44

**Comment by danmichaelo** [comment]
Thanks, it worked. I sent an email to PSF to check if it can be used.

**Comment by DavidMertz** [comment]
Hi, I'm David Mertz, chair of the Python Software Foundation Trademarks Committee.  I just wrote Dan with this info:

<hr/>

This modification of the Python "two snakes" logo is a dilutive derivative that is not allowed under our trademark policy, and we must insist against its use under US trademark law to avoid weakening our mark.

The PSF policy on use of our logo is quite liberal, and using the actual "two snakes" without modifying the shape is completely permitted as nominative use.  Creating a derived version by, e.g. putting brackets around it similar to those in the design linked, is fine as well (and/or rotating the two snakes by 45 degree, if that looks better, is still fine).

Thank you, David Mertz
Chair, Python Software Foundation Trademarks Committee

**Comment by waldyrious** [comment]
Cool, so that's even better: we can use the actual "two snakes" with the brackets. Rotating the logo sounds like a sensible idea, I think it would look better indeed. If nobody gets to it before then, I'll try to make a proposal tomorrow based on this.

**Comment by danmichaelo** [comment]
Would love to see that :+1:

**Comment by waldyrious** [comment]
Ok, here's the proposal:
![Imgur](http://i.imgur.com/vSnV1kt.png)
(source code [here](https://gist.github.com/waldyrious/e6127bc0565446e093ff))

Alternative version, with the snakes rotated the other way:
![Imgur](http://i.imgur.com/aVycJuY.png)

Any feedback welcome!

**Comment by c-martinez** [comment]
Very nice! Looks good to me.

**Comment by waldyrious** [comment]
@c-martinez which version do you prefer?

**Comment by c-martinez** [comment]
Slight preference for the second one, but look good.

**Comment by danmichaelo** [comment]
Cool (and honestly somewhat surprising) to see the rotated logo approach work out so well! I also have a slight preference for the second one, but only a slight :)

What do you think about adding slightly more weight on the brackets?

**Comment by PierreSelim** [comment]
I also have a slight preference for the second one (both are good imo)

**Comment by waldyrious** [comment]
And I prefer the second as well, so I guess that aspect is decided ;) as for the weight in the brackets, sure. Can't take care of that right now, but should be able to tweak it during the weekend.

@danmichaelo do you mean just the thickness, or the color as well? And should the thickness be increased equally in all parts, or just in the vertical bars?

**Comment by danmichaelo** [comment]
Just the thickness, I like the color. Equal thickness makes sense to me, but it's also possible that it would work well to have the vertical bars *slightly* thicker than the horisontal, not sure.

**Comment by waldyrious** [comment]
Sorry for the delay. How does this look?

![thicker brackets](http://i.imgur.com/WDRRG9E.png)

**Comment by danmichaelo** [comment]
Hm, I can't really decide which one I prefer... how about you?

**Comment by waldyrious** [comment]
I think thicker brackets work better at small scales, as they better match the thickness of the snakes and balance the logo overall. Try opening [the image](http://i.imgur.com/WDRRG9E.png) in a separate tab and zooming out.

**Comment by danmichaelo** [comment]
Agree! Should we add it to the readme and close the issue? :tada:

**Comment by danmichaelo** [comment]
Perhaps you can add both a svg and a png version to https://github.com/mwclient/mwclient/tree/master/docs/source ?

**Comment by waldyrious** [comment]
Definitely to both questions. Actually it was looking at the diff that introduced the sphynx docs that bumped this task back into my attention :)

**Comment by waldyrious** [comment]
@danmichaelo help me out with the rst please. Honestly, every time I have to deal with it I like it less and less. I lost some time trying to get it to center the logo (like [this](https://github.com/JuliaLang/julia/blob/master/README.md)), and eventually gave up. Now I'm trying to get the image to show up in a separate line (i.e. as a block), but can't figure out how to do that. Btw I suppose it might look better after the badges rather than before -- let me know what you think.

**Comment by danmichaelo** [comment]
Hm, quite annoying.. seems like the parser used by GitHub ignores `:align:`... If you paste this into http://rst.ninjs.org/ , it becomes center-aligned...

```
.. figure:: docs/source/logo.png
   :alt: Logo
   :align: center
```

**Comment by danmichaelo** [comment]
Image alignment not respected in reStructuredText : https://github.com/github/markup/issues/163

**Comment by danmichaelo** [comment]
Guess we just have to accept the situation: neither markdown or rst supports alignment. It's a bit frustrating that github allowd custom html  with markdown, but not with rst (I tried using `.. raw:: html`), but in the end mixing html into another markup language is not really a great solution anyways.

**Comment by waldyrious** [comment]
And what about converting the README back to md? :innocent: Now seriously, I think there are other benefits to md besides centering images, particularly the simpler markup and more widespread adoption. I've read somewhere that PyPI uses a `long_description` string if provided, and only resorts to displaying the README if one isn't found (I can try digging up the link if useful). Besides, makdown is (hopefully) going to be supported, according to https://github.com/pypa/readme/pull/3

**Comment by danmichaelo** [comment]
Thanks for pointing me to the issue. Too bad it stalled.

I think PyPI always use the `long_description`. If you look into the current [setup.py](https://github.com/mwclient/mwclient/blob/master/setup.py), it just puts the content of README.rst into `long_description`, more or less like this:

```python
long_description=open(os.path.join(os.path.abspath(os.path.dirname(__file__)),
    'README.rst')).read()
```

so we could easily replace that by a fixed string *if we want*. To make maintenance easier, i guess we could provide a slimmed down version with a link to the full README and the documentation at ReadTheDocs, and probably remove information that needs to be updated for each release. If you'd like to do the work involved, it's fine with me.

**Comment by waldyrious** [comment]
I saw [a post](https://coderwall.com/p/qawuyq/use-markdown-readme-s-in-python-modules) suggesting to use pandoc to generate long_description from a md README. Think we could use something like that?

**Comment by danmichaelo** [comment]
Could very well be. Give it a try :+1:

**Comment by waldyrious** [comment]
This has dragged on for too long. I rebased the branch and created a PR (#136). I noticed that https://github.com/pypa/readme_renderer/pull/3 has had some recent activity, so hopefully we may be closer to get a markdown readme.

Also, I added the logo to the mwclient organization :)

**Comment by waldyrious** [comment]
> Image alignment not respected in reStructuredText : [github/markup#163](https://github.com/github/markup/issues/163)

Just for future reference, this has now been [fixed](https://github.com/github/markup/issues/163#issuecomment-1282676832).
