### ISSUE TITLE
vim-mediawiki-editor, mwclient, personal wiki, *invalid json response*

### ISSUE THREAD

**Issue by bmarcinek** [mwclient/mwclient#94]
Hey,

I'm running [aquach/vim-mediawiki-editor](https://github.com/aquach/vim-mediawiki-editor/) to connect/edit my personal wiki.  When I try to connect to it, mwclient throws the following error

>mwclient errors.InvalidResponse: Did not get a valid JSON response from the server. Check that you used the correct hostname. If you did the server might be wrongly configured or experience temporary problems.

I can connect to en.wikipedia.org no problem though, so it doesn't seem to be a problem with Aquach's vim plugin.  I think it's a config problem with my personal wiki,... but I can't seem to find any documentation about how it should be config'd to allow mwclient to talk to it properly.

Any tips? Thanks!

**Comment by bmarcinek** [comment]
Solved.

The path to my wiki's API is '/', not '/w/'.

Changed line 55 in client.py from

>def __init__(self, host, path='/w/' ...

to

> def __init__ (self, host, path='/' ...

All is working now. :)

**Comment by lethosor** [comment]
You ought to be able to pass the `path` parameter to that constructor instead of modifying the library.

**Comment by bmarcinek** [comment]
Heh perhaps, if I were more clever with python...

**Comment by danmichaelo** [comment]
If https://github.com/aquach/vim-mediawiki-editor/pull/3 is merged, you can just set `g:mediawiki_editor_path` to `/`.

Very useful plugin btw! I wasn't aware of it.
