### ISSUE TITLE
Does not recognize new MediaWiki semantic versioning

### ISSUE THREAD

**Issue by hashar** [mwclient/mwclient#98]
From https://phabricator.wikimedia.org/T114365:
```
2015-10-01 13:41:55,841 DEBUG: 'production-logbot' got '!log Am I logging?'; Attempting to log.
2015-10-01 13:41:55,990 ERROR: Failed to log message
Traceback (most recent call last):
  File "/usr/lib/adminbot/adminlogbot.py", line 266, in on_pubmsg
    pageurl = adminlog.log(self.config, message, project, author)
  File "/usr/lib/adminbot/adminlog.py", line 15, in log
    site = mwclient.Site(config.wiki_connection, path=config.wiki_path)
  File "/usr/lib/pymodules/python2.7/mwclient/client.py", line 92, in __init__
    self.site_init()
  File "/usr/lib/pymodules/python2.7/mwclient/client.py", line 128, in site_init
    raise errors.MediaWikiVersionError('Unknown MediaWiki %s' % '.'.join(version))
MediaWikiVersionError: Unknown MediaWiki 1.27.0-wmf.1
```

**Comment by hashar** [comment]
From https://phabricator.wikimedia.org/T67306#683821

> Relative python awesomeness: there is a python module that support the semantic versioning spec.
> 
> Pypi: https://pypi.python.org/pypi/semantic_version/
> Doc: http://pythonhosted.org/semantic_version/

**Comment by danmichaelo** [comment]
Ok, so I read that this was fixed by upgrading mwclient. All versions from at least 0.7.0 should handle this fine, and perhaps even 0.6.5.

Anyways, I had a look at https://pypi.python.org/pypi/semantic_version . Nice package, but it fails (correctly) on the older version strings like "1.26.wmf24", which mwclient still need to support for some time.

**Comment by hashar** [comment]
@danmichaelo Thank you and sorry for the madness. As you have seen on Phabricator, our lib was fairly  outdated (from 2011).  I am very happy to see 0.7.0 supports both scheme without any troubles.

Thank you !
