### ISSUE TITLE
Problem with absolute imports

### ISSUE THREAD

**Issue by tosher** [mwclient/mwclient#99]
Hi!
I have a problem with using mwclient with python3.

If i want to use **mwclient** as first level module  - all works fine.
But if use **mwclient** as second level module (and so on)  - i have erros like:

```
...mwclient\__init__.py", line 26, in <module>
    from mwclient.errors import *
ImportError: No module named 'mwclient'
```

Because of mwclient is not on top level.

Example:

```
cli/__init__py  (is empty)
cli/cligo.py
cli/mwclient/
run.py
```

run.py

``` python
from cli import cligo
```

cligo.py

``` python
from cli import mwclient
# or
from . import mwclient
```

I trying to use latest version with Sublime Text 3 where each plugin is an imported module, and mwclient in it - as a submodule (subdirectory).

Some another moments with absolute imports:
- http://chimera.labs.oreilly.com/books/1230000000393/ch10.html#_discussion_171

> The downside of using an absolute name, such as mypackage.A, is that it hardcodes the top-level
> package name into your source code. This, in turn, makes your code more brittle and hard to work
> with if you ever want to reorganize it. For example, if you ever changed the name of the package,
> you would have to go through all of your files and fix the source code. Similarly, hardcoded names
> make it difficult for someone else to move the code around. For example, perhaps someone wants
> to install two different versions of a package, differentiating them only by name. If relative imports
> are used, it would all work fine, whereas everything would break with absolute names.

**Comment by danmichaelo** [comment]
Hm, I see… I'd really like to get rid of the absolute imports. The reason I still ended up using them was because if I run into problems with circular import if I use relative imports, like this:

```
tests/test_client.py:7: in <module>
    import mwclient
mwclient/__init__.py:27: in <module>
    from .client import Site, __ver__
mwclient/client.py:22: in <module>
    from .listing import *
mwclient/listing.py:6: in <module>
    from .image import Image
mwclient/image.py:1: in <module>
    from .listing import PageProperty, List
E   ImportError: cannot import name PageProperty
```

See #71 . Here is a quite good overview of the problem: [When are Python circular imports fatal?
](https://gist.github.com/datagrok/40bf84d5870c41a77dc6)

Perhaps I can break the cycle by using top-of-function imports in a few places.. Or perhaps injecting dependencies.

**Comment by danmichaelo** [comment]
I added [a new branch](https://github.com/mwclient/mwclient/tree/relative_imports) to test relative imports. It works when I move the import of Page/Image/Category in `listing.py` into the `__init__` method of `GeneratorList`. This feels a bit messy though.

**Comment by tosher** [comment]
I remember about case #71. But now, can't to say something about it.. :)

Thank you, i will try to use and research this branch.

**Comment by tosher** [comment]
https://github.com/mwclient/mwclient/wiki/Page.namespace
I have a similar code and with this version *page* in loop is a dictionary object, not Page :(
With old mwclient version (0.6.5) - all works ok.
Does it work fine on master branch?

**Comment by tosher** [comment]
```python
# Everywhere call __next__ instead of next:
class List(object):
    def __next__(self, full=False):
        # ...
        except StopIteration:
            # ...
            # return List.next(self, full=full)
            return List.__next__(self, full=full)
```

```python
class GeneratorList(List):
    def __next__(self):
            # info = List.next(self, full=True)
            info = List.__next__(self, full=True)
```
It works with my tests on py3, py2 - testing..

**Comment by tosher** [comment]
Plugin version in new [branch](https://github.com/tosher/Mediawiker/tree/mw_0.8.0/mwclient) works fine.
Some changes:
* <code>import listing</code>, not <code>from listing import ..</code>. The same with <code>errors</code>.
* iterators fixed in List, GeneratorList
* in Site.site_init some properties was added: *namespaces_canonical*, *namespaces_aliases* and inverted versions of *namespaces*, *namespaces_canonical*, *namespaces_aliases* for possibility to get namespace number by it's name in any language version.
* Sublime text not includes **six** module.. it's a part of mwlient in the plugin :)
